<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Address extends \Application\Entity\Address implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'idaddress', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'addressAllias', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'address', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'districtName', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'number', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'complement', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'status', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'user', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'typeAddress', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'city');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'idaddress', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'addressAllias', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'address', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'districtName', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'number', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'complement', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'status', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'user', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'typeAddress', '' . "\0" . 'Application\\Entity\\Address' . "\0" . 'city');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Address $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdaddress()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdaddress();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdaddress', array());

        return parent::getIdaddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdaddress($idaddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdaddress', array($idaddress));

        return parent::setIdaddress($idaddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressAllias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressAllias', array());

        return parent::getAddressAllias();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressAllias($addressAllias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressAllias', array($addressAllias));

        return parent::setAddressAllias($addressAllias);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', array());

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumber($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumber', array($number));

        return parent::setNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getComplement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplement', array());

        return parent::getComplement();
    }

    /**
     * {@inheritDoc}
     */
    public function setComplement($complement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplement', array($complement));

        return parent::setComplement($complement);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeAddress', array());

        return parent::getTypeAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeAddress($typeAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeAddress', array($typeAddress));

        return parent::setTypeAddress($typeAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistrictName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistrictName', array());

        return parent::getDistrictName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistrictName($districtName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistrictName', array($districtName));

        return parent::setDistrictName($districtName);
    }

}
