<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Advertising extends \Application\Entity\Advertising implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'idadvertising', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'text', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'address', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'item', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'contact', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'user', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'typeAdvertising', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'viewCount', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'createDate', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'status');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'idadvertising', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'text', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'address', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'item', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'contact', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'user', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'typeAdvertising', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'viewCount', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'createDate', '' . "\0" . 'Application\\Entity\\Advertising' . "\0" . 'status');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Advertising $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function timestamp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'timestamp', array());

        return parent::timestamp();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdadvertising()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdadvertising();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdadvertising', array());

        return parent::getIdadvertising();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdadvertising($idadvertising)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdadvertising', array($idadvertising));

        return parent::setIdadvertising($idadvertising);
    }

    /**
     * {@inheritDoc}
     */
    public function getText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getText', array());

        return parent::getText();
    }

    /**
     * {@inheritDoc}
     */
    public function setText($text)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setText', array($text));

        return parent::setText($text);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getItem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItem', array());

        return parent::getItem();
    }

    /**
     * {@inheritDoc}
     */
    public function setItem($item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItem', array($item));

        return parent::setItem($item);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getViewCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViewCount', array());

        return parent::getViewCount();
    }

    /**
     * {@inheritDoc}
     */
    public function addViewCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addViewCount', array());

        return parent::addViewCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDate', array());

        return parent::getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', array());

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact($contact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', array($contact));

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeAdvertising()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeAdvertising', array());

        return parent::getTypeAdvertising();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeAdvertising($typeAdvertising)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeAdvertising', array($typeAdvertising));

        return parent::setTypeAdvertising($typeAdvertising);
    }

}
