<div class="container whiteBackground">
	<!-- Área de Login -->
	<div class="row">
		<div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 navegacaoProduto">
			<a href="#" class="pull-left">< Voltar para Página Inicial</a>
		</div>
		<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 navegacaoProduto">
			<a href="#" class="pull-right">Nova Busca ></a>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="headerTitle">
				<h1>Anúncios para Pessoa Jurídica</h1>
			</div>
		</div>
	</div>

	<!-- Login -->
	<div class="row">

		<div class="container">
			<div class="row">
				<div class="col-sm-12 col-lg-12"></div>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-8">

				<h4 align="center">DIVUGUE SUA MARCA</h4>
				<h4 align="center">VISIBILIDADE NO PORTAL DE CLASSIFICADOS ONLINE
					DEDICADO AO MERCADO DE TRANSPORTE</h4>
				<div align="center">
					<strong>FORMATOS E PROJETOS ESPECIAIS</strong>
				</div>
				<div align="center">Converse conosco e conheça os formatos
					publicitários. Nos encaminhe um email.</div>



				<div class="well well-sm">
					<form>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="name"> Nome</label> <input type="text"
										class="form-control imput-lg" id="name"
										placeholder="Digite o seu nome..." required="required" />
								</div>
								<div class="form-group">
									<label for="email"> Email </label>
									<div class="input-group">
										<span class="input-group-addon"><span
											class="glyphicon glyphicon-envelope"></span> </span> <input
											type="email" class="form-control imput-lg" id="email"
											placeholder="Coloque o seu email..." required="required" />
									</div>
								</div>
								<div class="form-group">
									<label for="subject"> Assunto</label> <select id="subject"
										name="subject" class="form-control imput-lg"
										required="required">
										<option value="na" selected="">Categoria:</option>
										<option value="service">Suporte</option>
										<option value="suggestions">Sugestões</option>
										<option value="product">Comercial</option>
									</select>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="name"> Mensagem</label>
									<textarea name="message" id="message"
										class="form-control imput-lg" rows="9" cols="25"
										required="required" placeholder="Escreva a sua Mensagem..."></textarea>
								</div>
							</div>
							<div class="col-md-12">
								<button type="submit" class="btn btn-primary pull-right"
									id="btnContactUs">Enviar Mensagem</button>
							</div>
						</div>
					</form>
				</div>
			</div>
			<div class="col-md-4">
				<form>
					<legend>
						<span class="glyphicon glyphicon-globe"></span> Informações de
						Contato
					</legend>
					<address>
						<strong>Brik e Brak, Inc.</strong><br> São Paulo, Brasil<br> <br>
						<abbr title="Telefone"> Telefone: </abbr> (123) 456-7890
					</address>
					<address>
						<strong>E-mail de Contato:</strong><br> <a href="mailto:#">contato@brikebrak.com.br</a>
						<a href="mailto:#">atendimento@brikebrak.com.br</a> <a
							href="mailto:#">comercial@brikebrak.com.br</a>
					</address>
				</form>
			</div>
		</div>
	</div>
</div>