<div class="container whiteBackground">
	<!-- Navegação Produto -->
	<div class="row">
		<div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 navegacaoProduto">
			<a href="#" class="pull-left">< Voltar para Página Inicial</a>
		</div>
		<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 navegacaoProduto">
			<a href="#" class="pull-right">Nova Busca ></a>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="headerTitle">
				<h1>Planos</h1>
			</div>
		</div>
	</div>

	<!-- Inicio Fisico -->
	<div class="row">
		<h4>PESSOA FÍSICA</h4>
		<div class="col-md-4">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h4 class="text-center">1 MÊS</h4>
				</div>
				<div class="panel-body text-center">
					<p class="lead">
						<strong>GRÁTIS</strong>
					</p>
				</div>
				<ul class="list-group list-group-flush text-center">
					<li class="list-group-item"><i class="icon-ok text-danger"></i>Edição
						de Anúncio Ilimitado</li>

				</ul>
				<div class="panel-footer">
					<a class="btn btn-lg btn-block btn-danger" href="#">ASSINAR</a>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h4 class="text-center">3 MESES</h4>
				</div>
				<div class="panel-body text-center">
					<p class="lead">
						<strong>R$ 36,00</strong>
					</p>
				</div>
				<ul class="list-group list-group-flush text-center">
					<li class="list-group-item"><i class="icon-ok text-danger"></i>Edição
						de Anúncio Ilimitado</li>

				</ul>
				<div class="panel-footer">
					<a class="btn btn-lg btn-block btn-info" href="#">ASSINAR</a>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h4 class="text-center">6 MESES</h4>
				</div>
				<div class="panel-body text-center">
					<p class="lead">
						<strong>R$ 68,40</strong>
					</p>
				</div>
				<ul class="list-group list-group-flush text-center">
					<li class="list-group-item"><i class="icon-ok text-danger"></i>Edição
						de Anúncio Ilimitado</li>

				</ul>
				<div class="panel-footer">
					<a class="btn btn-lg btn-block btn-success" href="#">ASSINAR</a>
				</div>
			</div>
		</div>
	</div>

	<!-- end fisico -->

	<!-- inicio juridico -->

	<div class="row">
		<h4>PESSOA JURÍDICA</h4>
		<div class="col-md-4">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h4 class="text-center">3 MESES</h4>
				</div>
				<div class="panel-body text-center">
					<p class="lead">
						<strong>R$ 35,00</strong>
					</p>
				</div>
				<ul class="list-group list-group-flush text-center">
					<li class="list-group-item"><i class="icon-ok text-danger"></i>Edição
						de Anúncio Ilimitado</li>

				</ul>
				<div class="panel-footer">
					<a class="btn btn-lg btn-block btn-danger" href="#">ASSINAR</a>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="panel panel-info">
				<div class="panel-heading">
					<h4 class="text-center">6 MESES</h4>
				</div>
				<div class="panel-body text-center">
					<p class="lead">
						<strong>R$ 66,50</strong>
					</p>
				</div>
				<ul class="list-group list-group-flush text-center">
					<li class="list-group-item"><i class="icon-ok text-danger"></i>Edição
						de Anúncio Ilimitado</li>

				</ul>
				<div class="panel-footer">
					<a class="btn btn-lg btn-block btn-info" href="#">ASSINAR</a>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h4 class="text-center">1 ANO</h4>
				</div>
				<div class="panel-body text-center">
					<p class="lead">
						<strong>R$ 130,00</strong>
					</p>
				</div>
				<ul class="list-group list-group-flush text-center">
					<li class="list-group-item"><i class="icon-ok text-danger"></i>Edição
						de Anúncio Ilimitado</li>

				</ul>
				<div class="panel-footer">
					<a class="btn btn-lg btn-block btn-success" href="#">ASSINAR</a>
				</div>
			</div>
		</div>
	</div>

</div>
