<div class="container whiteBackground">
	<!-- Área de Login -->
	<div class="row">
		<div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 navegacaoProduto">
			<a href="/" class="pull-left">< Voltar para Página Inicial</a>
		</div>
		<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 navegacaoProduto">
			<!--a href="#" class="pull-right">Nova Busca ></a-->
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="headerTitle">
				<h1>Publicidade</h1>
			</div>
		</div>
	</div>

	<!-- Login -->
	<div class="row">
		<div class="col-xs-12">

			<p>DIVUGUE SUA MARCA</p>
 
            - VISIBILIDADE NO PORTAL DE CLASSIFICADOS ONLINE DEDICADO AO MERCADO DE TRANSPORTE<br>
            - FORMATOS E PROJETOS ESPECIAIS<br>
            <p>
            É MUITO FÁCIL ANUNCIAR SUA CAMPANHA!
            <br><br>
            <a href="<?php echo $this->url('atendimento') ?>">Converse conosco e conheça os formatos publicitários.</a>
            </p>

		</div>
	</div>
</div>


 