<div class="container whiteBackground">
					<!-- Navegação Produto -->
					<div class="row">
						<div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 navegacaoProduto">
							<a href="/" class="pull-left">< Voltar para Página Inicial</a>
						</div>
						<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 navegacaoProduto">
							<!--a href="#" class="pull-right">Nova Busca ></a-->
						</div>
					</div>

					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<div class="headerTitle">
								<h1>Quem Somos</h1>
							</div>
						</div>
					</div>

					<!-- DETALHES DO PRODUTO -->
					<div class="row">
                    <div class="col-md-8">

           
           	O BrikeBrak, é uma empresa nacional que apresenta-se ao mercado com o compromisso proporcionar constante desenvolvimento em seus serviços. 
            Disponibiliza um portal de classificados moderno, inovador e simplificado dedicado ao mercado de transportes.
            Interessados em comprar, vender, anunciar produtos, serviços e curriculos profissionais, tem no BrikeBrak o meio de atingir o público nacional.
            Suas políticas de qualidade primam pelo melhor serviço a seus usuários e anunciantes e são constantemente atualizadas.
            Campanhas de gratuidade, ofertas, descontos podem ser apresentadas aos a qualquer momento, podendo ser finitas ou não.
            <br /><br />
            Além do diferencial de ser direcionado ao mercado de transporte, o BrikeBrak disponibiliza a opção ao usuário de poder editar suas ofertas quantas vezes desejar durante o prazo do plano adquirido.
            <br /><br />
            Bons negocios.
                  

                    </div>
					  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
					    <div class="col-lg-12">
								<img src="assets/images/PUBLICIDADE.jpg" width="300" height="180" alt=""/>
                                <br><br>
								<img src="assets/images/PUBLICIDADE.jpg" width="300" height="180" alt=""/>
								<br /><br />
                                
					  </div>
					</div>
				</div>
			</div>