<div class="container whiteBackground">
					<!-- Navegação Produto -->
					<div class="row">
						<div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 navegacaoProduto">
							<a href="/" class="pull-left">< Voltar para Página Inicial</a>
						</div>
						<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 navegacaoProduto">
							<!--a href="#" class="pull-right">Nova Busca ></a-->
						</div>
					</div>

					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<div class="headerTitle">
								<h1>Rastreadores</h1>
							</div>
						</div>
					</div>

					<!-- DETALHES DO PRODUTO -->
					<div class="row">
                    <div class="col-md-8">

<p> Aguardando conteúdo</p>
           
           	Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.

      

                    </div>
					  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
					    <div class="col-lg-12">
								<img src="assets/images/PUBLICIDADE.jpg" width="300" height="180" alt=""/>
                                <br><br>
								<img src="assets/images/PUBLICIDADE.jpg" width="300" height="180" alt=""/>
                                
					  </div>
					</div>
				</div>
			</div>