
<div class="container whiteBackground">
	<!-- Navegação Produto -->
	<div class="row">
		<div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 navegacaoProduto">
			<a href="#" class="pull-left">< Voltar para Página Inicial</a>
		</div>
		<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 navegacaoProduto">
			<a href="#" class="pull-right">Nova Busca ></a>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="headerTitle">
				<h1>Termos de Uso</h1>
			</div>
		</div>
	</div>

	<!-- DETALHES DO PRODUTO -->
	<div class="row">
		<div class="col-md-8">

			<div align="justify">
			<pre>
			CONSIDERAÇÕES
- Provedor:  BRIKEBRAK 
- Domínios: BRIKEBRAK.com.br, BRIKEBRAK.com, BRIKEBRAK.net
- Propriedade da: SAS GERENCIAMENTO DE RISCOS, Rua Cabo Verde, 140 , Vila Olímpia, São Paulo – SP, CEP 04550-080, registrada no CNPJ/MF sob o nº. 14.537.316/0001-21, 
- URL:  www.BRIKEBRAK.com.br. (.com e .net).
A)  Consiste o serviço comercializado pela BRIKEBRAK na disponibilização aos Usuários de internet e Smartphone de uma plataforma para oferta de bens e serviços. Portanto, atua hospedando conteúdo de terceiros postados por seus Usuários (“Usuário(s)”).
B) Assim, o Usuário publica dados no site da BRIKEBRAK com todos os detalhes possíveis, inclusive seus dados pessoais para contato direto, negociação e conclusão da transação, sendo esta última ocorrida fora do ambiente do site BRIKEBRAK (compra e venda).
C) O Usuário que utiliza o site BRIKEBRAK para ofertar, ou ainda encontrar as informações que procura, o faz por sua vontade, conta e risco, sem que a BRIKEBRAK seja responsável pela precisão dos dados especificados pelos Usuários, nem pela qualidade e demais detalhes daquilo que é ofertado. 
A BRIKEBRAK não participa e/ou interfere, de qualquer forma, na negociação e/ou efetivação de quaisquer transações (venda e compra).
A BRIKEBRAK tem como direcionamento, mas não se limitando, o mercado de transporte (ofertas e procuras por caminhões, onibus, utilitários, implementos, suas peças, empresas de serviços, revendas, seguros, e ainda curriculos profissionais).
MODALIDADES:
D) Ofertas bens, serviços e curriculos são pagas mediante planos descritos no site
D.1) Buscas de bens, serviços e curriculos são livres gratuitas pela URL 
E) As taxas cobradas pela BRIKEBRAK fazem referência as demandas dos Usuários no site e APP. Conforme Politica de Uso e Acesso (P&A) tem disponibildade finita e temporal, podendo ser contratados planos que permitem exposição/buscas,  mensal, semestral e anual.
F) A BRIKEBRAK não garante que haja a negociação e conclusão de uma transação, tampouco reembolsará o Usuário em caso de insucesso. Suas taxas em resumo fazem jus ao uso do site (disponibilização de informações).
Modo de utilização (não exaustivo) sequências de utilização:


- OFERTAS E PROCURAS POR CAMINHÕES, ONIBUS, UTILITÁRIOS, IMPLEMENTOS, SUAS PEÇAS, EMPRESAS DE SERVIÇOS, REVENDAS, SEGUROS, E AINDA CURRICULOS PROFISSIONAIS.

1) Via URL, 

2) Cadastrar login, senha, dados e escolha do que pretende ofertar.

3) A oferta via URL  é paga mediante aderência a um plano.

4) Sua opção permanece em disponível no site durante todo período correspondente ao plano escolhido, podendo ser editado quantas vezes necessitar (o espaço ¨alugado¨no site BRIKEBRAK é de controle de conteúdo do comprador do plano durante todo perírodo escolhido). Ex: Venda de veículo em um plano mensal: Realizou negócio em 4 dias, é possivel publicar outra venda entretanto tem-se a restrição (mesma modalidade de escolha ¨publicação de venda de veículo e dados cadastrais).

5) Inspirado o prazo de um plano, sem que haja renovação, as publicações são retiradas automaticamente do SITE.


1. ADESÃO
1.1. Oferece a BRIKEBRAK ao Usuário recursos  (“Serviços”) para o uso da plataforma de dado virtual regido por estas Politicas de Uso e Acesso da BRIKEBRAK (P&A).
1.2. A adesão aos Serviços implica na devida vontade, compreensão, aceitação e vinculação automática do Usuário as P&A. Ao utilizar os Serviços oferecidos, o Usuário concorda em atender a todas e quaisquer diretrizes dispostas nestas P&A.
1.3. Estas P&A poderão sofrer alterações temporaneas, sejam por questões legais ou estratégicas da BRIKEBRAK. O Usuário concorda e reconhece que é de sua única e inteira responsabilidade a verificação periódica destas P&A. A BRIKEBRAK poderá informar, por sua liberalidade, ao Usuário sobre alterações significativas nas P&A através de avisos em seu site.
 1.4. Caso haja objeção a P&A e/ou alterações posteriores desta, ou eventualmente insatisfação com os Serviços oferecidos pela BRIKEBRAK, o Usuário poderá cessar o uso imediatamente.

2. POLÍTICA 
2.1. É de conhecimento do Usuário de que todos os dados disponíveis no site são produzidos e disponibilizados por terceiros, sem que haja qualquer tipo de acompanhamento e verificação prévia da BRIKEBRAK. 
A BRIKEBRAK não Interfere (controla, edita, monitora) e não é, em nenhuma hipótese, responsável pelos dados fornecidos ou qualquer outro material disponibilizado ou não através dos Dados submetidos ao site por seus Usuários. 
Excessão: publicões que envolverem imagens podem ser submetidas a vistoria rápida da equipe BRIKEBRAK afim de evitar-se que conteúdos impróprios (pornograficos, ofensivos, ilegais) sejam publicados, entretanto, não há edição do anuncio por esta última. Existindo eventuais ocorrencias, é iniciado contato com o publicante para que este efetue correções.
O Usuário concorda que ao utilizar o site poderá se expor a conteúdo eventualmente, inexato, enganoso ou censurável.
2.1.1. Concorda o Usuário que deve avaliar e assumir os riscos associados a ao Conteúdo e/ou Dado submetido ao site. Em nenhuma circunstância, a BRIKEBRAK será responsável, pelo Conteúdo e/ou pelas perdas ou danos incorridos em função do uso, submissão e acesso de qualquer Conteúdo e/ou Dado listado, enviados ou disponibilizados através do site.
2.1.2. O Usuário reconhece que a BRIKEBRAK terá o direito de, a seu exclusivo critério, recusar, excluir ou mover qualquer Conteúdo e/ou Dado disponibilizado no site, seja por violação as P&A ou por quaisquer outras razões de ordem ética, econômica, legal ou moral. 
2.2. O Usuário é o único responsável por todo o Dado e/ou Conteúdo de sua autoria ou por ele divulgado, transmitido ou associado a link disponibilizado no/ou através do site; assim como pelo seu uso, divulgação ou publicação, devendo o Usuário manter a BRIKEBRAK, seus funcionários, parceiros e controladores livres e indenes de toda e qualquer consequência advinda de seus atos/ omissões, inclusive em relação a terceiros.
2.2.1. Com relação ao Dado e/ou Conteúdo divulgado, transmitido ou associado a link no Site, o Usuário declara que:
(i) é o titular dos direitos e/ou possui as autorizações e vontades necessárias para divulgar o Conteúdo e permitir que a BRIKEBRAK o utilize e/ou eventualmente o formate para melhor disposição no Site, e;
(ii) tem o consentimento expresso por vontade, licença e/ou permissão de toda e qualquer pessoa identificável no Conteúdo, seja ela para usar seu nome e/ou sua imagem.
2.3. A BRIKEBRAK não exerce influência para ratificar, editar, aprovar ou monitorar previamente qualquer Dado/Conteúdo expresso no Site e não assume quaisquer responsabilidades a eles relacionadas.
2.3.1. O Usuário desde já aceita e concorda que não é permitida pela  BRIKEBRAK, a submissão ao Site Dados e/ou Conteúdos de qualquer forma relacionados a atividades que desrespeitem direitos de propriedade intelectual, ou qualquer outra violação a direitos de terceiros, e poderá remover todo o Dado e/ou Conteúdo inadequado, quando devidamente notificada de que o mesmo viola direitos de terceiros ou a legislação brasileira.
2.3.2. A BRIKEBRAK se reserva o direito de remover o Dado e/ou qualquer Conteúdo submetido ao Site sem aviso prévio. 
A BRIKEBRAK poderá, a seu exclusivo critério, suspender ou cancelar, de qualquer forma que seja, o cadastro e/ou acesso do usuário ao site em caso de infração a qualquer das disposições destas P&A. 
A BRIKEBRAK também se reserva o direito de decidir, a seu único e exclusivo critério, quais Conteúdos e/ou Dados entende como inadequados. 
2.4. Existem modalidades de utilização que, a critério exclusivo da BRIKEBRAK, são cobradas taxas para postagem de Conteúdo e/ou Dado em determinadas áreas do site.
2.4.1. No caso de remoção de Conteúdo e/ou Dado por desrespeito às Condições de Uso da BRIKEBRAK, não serão reembolsadas eventuais taxas pagas pelo destaque do dado ou qualquer outro serviço, 

3. POLÍTICA DE CONTEÚDO E PENALIDADES
3.1. A BRIKEBRAK não permite, e desde já considera como inadequado, quaisquer Dados e/ou Conteúdos enquadrados na lista abaixo. Desta forma, o Usuário compromete-se a não divulgar, enviar por e-mail, ou disponibilizar de qualquer outro modo, Conteúdo e/ou Dado:
(a)Ilícito;
(b) Protegido por direitos autorais, segredo comercial, industrial ou de terceiros; a menos que o Usuário tenha permissão do titular de tais direitos para divulgar o Conteúdo e/ou Dado;
 (c) Que inclua informações pessoais ou que permitam a identificação de terceiro sem seu expresso consentimento;
(d) Falso, fraudulento, enganoso 
3.1.1. Além disso, o Usuário concorda :
(a) Em não entrar em contato com qualquer Usuário que peça para não ser contatado;
 (b) Em não obter, guardar, divulgar, comercializar e/ou utilizar dados pessoais sobre outros Usuários para fins comerciais ou ilícitos;
 (c ) Em não divulgar Conteúdo e/ou Dado que não seja nacional;

4. ACESSO AO SITE
4.1. A BRIKEBRAK concede ao Usuário autorização (revogável e sem aviso prévio, não-exclusiva e limitada), para acessar o Site e utilizá-lo de modo pessoal.
4.2 O uso do Site para além do âmbito de acesso autorizado pela BRIKEBRAK implicará na revogação imediata da licença aqui concedida sem prejuízo das penalidades legais.



5. PUBLICIDADE
5.1. A BRIKEBRAK oferece a seus Usuários serviços pagos regulares  denominados PUBLICIDADE  que possibilita ao Usuário dar maior visibilidade ao seu Dado, mediante pagamento de um valor determinado.
5.1.1. A BRIKEBRAK utiliza os serviços da  XXXXXXX (www.dinheiromail.com.br) para processar o pagamento do valores dos planos e, por tanto, será necessário cadastro junto ao mesmo.
5.1.1.1. O Usuário aceita e concorda que a XXXXXXX, ou qualquer outro provedor de serviços online eventualmente utilizado para processar estes pagamentos, atua por sua única e exclusiva responsabilidade e o Usuário está ciente de que esta transação será regida pelos termos de uso aceitos no momento do cadastro junto a este provedor
5.1.1.2. O Usuário aceita e concorda que a BRIKEBRAK é alheia a esta transação e não responderá, sob qualquer hipótese, pela segurança e qualidade desta.
5.1.2. Este valor pago não será, em qualquer hipótese, reembolsado pela BRIKEBRAK.
5.2. A BRIKEBRAK não garante qualquer resultado relacionado ao PUBLICIDADE.

6. NOTIFICAÇÃO SOBRE INFRAÇÕES
6.1. Caso qualquer pessoa, Usuário ou não, se sentir lesado em relação a qualquer Dado e/ou Conteúdo, poderá encaminhar à BRIKEBRAK notificação por escrito solicitando sua retirada. Email: atendimento@brikebrak.com.br.  No entanto, para não prejudicar Usuários de boa-fé, a retirada do Dado e/ou Conteúdo do Site pela BRIKEBRAK será dependente de efetiva comprovação ou forte evidência da ilegalidade ou infração à lei, direitos de terceiros e/ou aos P&A.
6.3. As notificações deverão ainda conter as seguintes informações: 
a) Assinatura física ou eletrônica da pessoa supostamente lesada, ou, se for o caso, do titular do direito intelectual violado;
b) Identificação do objeto protegido por direitos intelectuais que tenha sido violado, se for o caso;
c) Identificação do material que supostamente representa a infração, código do(s) Dado(s) e/ou link do(s) Dado(s), ou, em caso de não se tratarem de Dados, informações necessárias para a devida identificação do Conteúdo;
d) Declaração de que o notificante possui elementos suficientes para embasar a alegação de violação legal; e
e )Declaração de que as informações contidas na notificação são precisas e verdadeiras, sob pena de incorrer nas consequentes responsabilidades cíveis e penais, e de que o notificante está autorizado a agir em nome do titular do direito supostamente violado.
6.4. As notificações deverão ser encaminhadas à BRIKEBRAK através de email. Apenas as notificações relacionadas a efetiva violação de direitos devem ser encaminhados. 
Quaisquer naturezas de opinião como, comentários, sugestões, críticas, solicitações de suporte técnico e outras comunicações devem ser direcionadas ao atendimento ao cliente da BRIKEBRAK clicando no LINK “FALE CONOSCO” no site. 

7. POLÍTICA DE PRIVACIDADE E DIVULGAÇÃO DE INFORMAÇÕES
7.1. O Usuário desde já autoriza a BRIKEBRAK a,  preservar, armazenar todos os Dados e/ou Conteúdos submetidos ao site, bem como todos os seus dados pessoais, a exemplo de endereços de e-mail, endereços de IP (Internet Protocol), informações de data e horário de acesso, entre outras informações. O Usuário também autoriza a BRIKEBRAK a informar e/ou divulgar estes dados em caso de exigência legal ou se razoavelmente necessárias para: cumprir com o devido processo legal; fazer cumprir estes P&A; responder a alegações de suposta violação de direitos de terceiros e de divulgação indevida de informações para contato de terceiros (por exemplo, número de telefone, endereço residencial), e para proteger os direitos, a propriedade ou a segurança de terceiros ou da própria BRIKEBRAK e de seus Usuários.
7.2. A BRIKEBRAK poderá utilizar empresas de processamento de cartões de crédito e/ou de gestão de meios de pagamentos online terceirizadas, assim como empresas para monitorar o tráfego do Site, que, em alguns casos, poderão armazenar e coletar informações e dados do Usuário.
7.3. A utilização do Site implica no consentimento do Usuário para coleta, armazenamento e uso das informações pessoais fornecidas e suas atualizações, dados de tráfego, endereços IP, entre outros.
7.4. A BRIKEBRAK poderá utilizar cookies para administrar as sessões dos Usuários e armazenar preferências, rastrear informações, idioma selecionado, entre outros. Cookies poderão ser utilizados independentemente de cadastro do Usuário.
7.4.1. Em alguns casos, prestadores de serviços terceirizados poderão utilizar cookies no Site, que a BRIKEBRAK não controla nem acessa. Tais cookies não são regulados por estes Termos e Condições.
7.5. O Usuário tem a opção de aceitar ou recusar o uso de cookies em seu computador, independente de cadastro no Site, configurando seu navegador como desejar. A recusa do uso de cookies pode, contudo, resultar na limitação do acesso do Usuário a certas ferramentas disponíveis no Site, dificuldades no login, uso do Fórum BRIKEBRAK e na ferramenta de comentários.
7.6. Considerando que a BRIKEBRAK poderá realizar parcerias com terceiros, eventualmente estes poderão coletar informações de Usuários como endereço IP, especificação do navegador e sistema operacional. Estes Termos e Condições não se aplicam às informações pessoais fornecidas aos terceiros e por eles armazenadas e utilizadas.
7.7. O Site poderá, eventualmente, conter links para sites de terceiros. A BRIKEBRAK não se responsabiliza pelo conteúdo ou pela segurança das informações do Usuário quando acessar sites de terceiros. Tais sites podem possuir suas próprias políticas de privacidade quanto ao armazenamento e conservação de informações pessoais, completamente alheias à BRIKEBRAK.
7.8. A BRIKEBRAK poderá trabalhar com empresas terceirizadas de propaganda para a divulgação de dados durante visitas a seu site. Tais empresas poderão coletar informações sobre as visitas de Usuários ao site da BRIKEBRAK, no intuito de fornecer dados personalizados sobre bens e serviços do interesse do Usuário. Tais informações não incluem nem incluirão nome, endereço, e-mail ou número de telefone do Usuário.
7.8.1. No site da BRIKEBRAK, fornecedores terceirizados poderão utilizar cookies para divulgar dados relacionados com os Dados e/ou Conteúdos. O uso de cookies DART permite a divulgação de dados aos Usuários com base em suas visitas ao site da BRIKEBRAK e a outros websites. 
7.9. Ao publicar um dado na BRIKEBRAK, o Usuário compreende que os dados e o Conteúdo são públicos e acessíveis a terceiros, podendo ser listados nos resultados de ferramentas de pesquisa disponiveis na WEB e outros e no cache dessas ferramentas de pesquisa, em feeds e outros websites por acordos comerciais entre a BRIKEBRAK e outras prestadoras de serviço. 
O Usuário compreende que é de responsabilidade de cada uma dessas ferramentas de pesquisa, websites ou recursos RSS manter seus índices e cache atualizados e remover o Conteúdo de seus índices e cache, pois não é possível que a BRIKEBRAK exerça influência sobre eles.
7.10. A BRIKEBRAK poderá utilizar as informações e/ou dados fornecidos e/ou coletados pelo Usuário para:
(i) Aplicar estes P&A;
(ii) Acompanhar as atividades do Usuário, utilizando palavras chave de pesquisas e novos dados para administrar mais efetivamente o tráfego no Site;
(ii) Prestar serviços ao Usuário;
(iv) Criar e administrar Contas de Usuário; e
(v) Prestar assistência.
7.11. A BRIKEBRAK poderá, ainda, compartilhar informações coletadas, como a capacidade do navegador ou o sistema operacional do Usuário, com os prestadores de serviços terceirizados, no intuito de compreender melhor quais dados e serviços podem ser de interesse do Usuário.
7.12. É reservado à BRIKEBRAK o direito de bloquear o acesso ao Site de Usuários alocados em outros países.
7.13. A BRIKEBRAK se reserva o direito de reter informações pelo período que entender necessário para o bom cumprimento de seus negócios, mesmo após o encerramento da conta do Usuário, salvo manifestação expressa do Usuário em sentido contrário.
7.14. A BRIKEBRAK não processa pagamentos diretamente e não armazena informações de cartões de crédito dos Usuários. É utilizada a tecnologia “secured socket layer” (SSL) para o processamento de transações com prestadores de serviços terceirizados.
7.15. As informações e dados cadastrais do Usuário podem ser protegidas por senha e nome de Usuário exclusivos, pessoais e intransferíveis, que não devem ser divulgadas, quer pela BRIKEBRAK, quer pelo próprio Usuário.
7.16. As informações referentes ao Serviço são mantidas em uma base de dados localizada no Brasil e eventualmente em outros paises.
7.17. O Usuário desde já declara estar ciente que a BRIKEBRAK não assume nenhuma responsabilidade em caso de roubo, perda, alteração ou uso indevido de suas informações pessoais e do Conteúdo como um todo, inclusive na hipótese de informações fornecidas a prestadores de serviços terceirizados ou a outros Usuários e na hipótese de descumprimento destes P&A por prestadores de serviços terceirizados.
7.18. Participação no SITE BRIKEBRAK ou utilização da ferramenta de Comentários.
7.18.1. O Nome de Usuário do Usuário será divulgado em suas postagens no SITE.
7.18.2. O nome e e-mail do Usuário somente serão divulgados em seus comentários quando neles inclusos pelo próprio Usuário.
7.18.3. A BRIKEBRAK recomenda que o Usuário não divulgue nestas ferramentas, ou em qualquer outro Conteúdo, informações que o Usuário não deseja que sejam públicas.
7.19. O Usuário não precisa se cadastrar para postar ou responder a Dados no Site. Ao utilizar o site da BRIKEBRAK para postar ou responder dados o Usuário manifesta aceite aos Politica de Uso BRIKEBRAK, a BRIKEBRAK poderá enviar ao Usuário notificações sobre dados, promoções, conteúdos especiais e notificações, exigidas legalmente ou não.
7.19.1. O Usuário poderá optar por não receber via e-mail determinadas mensagens, como newsletters, recomendações de compra e venda no Site, avisos de recebimento de comentários em seus dados e avisos de autorização para atualização de suas mensagens. Tais preferências não serão alteradas sem o devido consentimento do Usuário.

8. DIREITOS DE PROPRIEDADE INTELECTUAL
8.1. Os elementos e/ou ferramentas encontrados no site, com exceção dos Conteúdos e/ou Dados submetidos por Usuários são de titularidade ou licenciados pela BRIKEBRAK, sujeitos aos direitos intelectuais de acordo com as leis brasileiras e tratados e convenções internacionais dos quais o Brasil seja signatário. Apenas a título exemplificativo, entendem-se como tais: textos, softwares, scripts, imagens gráficas, fotos, sons, músicas, vídeos, recursos interativos e similares, marcas, marcas de serviços, logotipos e “look and feel”.
8.2. Os elementos e/ou ferramentas que são disponibilizados para o Usuário no site os são tão e somente no ESTADO EM QUE SE ENCONTRAM e apenas para sua informação e uso pessoal na forma designada pela BRIKEBRAK. Tais elementos e/ou ferramentas não podem ser usados, copiados, reproduzidos, distribuídos, transmitidos, difundidos, exibidos, vendidos, licenciados ou, de outro modo, explorados para quaisquer fins, sem o consentimento prévio e por escrito da BRIKEBRAK.
8.3. A BRIKEBRAK reserva a si todos os direitos que não foram expressamente previstos em relação ao Site, aos seus elementos e/ou ferramentas. O Usuário compromete-se a não usar, reproduzir ou distribuir quaisquer elementos e/ou ferramentas que não sejam expressamente permitidos pela BRIKEBRAK – inclusive o uso, reprodução ou distribuição para fins comerciais dos Dados e/ou Conteúdos extraídos do site. Caso o Usuário faça qualquer cópia, seja ela via download ou impressão, dos elementos e/ou ferramentas da BRIKEBRAK para uso exclusivamente pessoal, deverá preservar todos os direitos de propriedade intelectual inerentes. O Usuário concorda em não burlar, desativar ou, de alguma forma, interferir em recursos e/ou ferramentas relacionados à segurança do site, sob pena de incorrer nas medidas judiciais cabíveis.

9. GARANTIA DE DADO E/OU CONTEÚDO
9.1. O Usuário está ciente de que, ao acessar o Site da BRIKEBRAK, (i) estará exposto a Dados e/ou Conteúdos de uma variedade de fontes não validadas ou garantidas previamente pela BRIKEBRAK, e (ii) que a BRIKEBRAK não é responsável pela sua precisão, veracidade, legalidade, licitude, utilidade e/ou segurança destes Dados e/ou Conteúdos.
9.2. A BRIKEBRAK também não garante o sucesso nas transações ou informações buscadas no site, na forma descrita no item 10 adiante.

10. LIMITAÇÃO DE RESPONSABILIDADE
O Usuário se compromete a defender, indenizar e isentar de qualquer responsabilidade a BRIKEBRAK, seus executivos, subsidiárias, afiliados, sucessores, prepostos, diretores, agentes, prestadores de serviços, fornecedores e funcionários com relação a toda e qualquer reclamação, perda, dano, obrigação, custos, dívidas ou despesas (incluindo, entre outros, honorários advocatícios e custas processuais) incorridas em razão de: (i) mau uso e acesso do Site da BRIKEBRAK; (ii) violação e/ou não observância de quaisquer dispositivos destes P&A; (iii) violação de qualquer direito de terceiros, incluindo, mas sem se limitar a, qualquer direito proprietário ou de privacidade; ou (iv) qualquer reclamação de que algum Dado e/ou Conteúdo causou dano a terceiros. Esta defesa e obrigação de indenização subsistirão a estes P&A e ao uso e/ou acesso do site.



11. TRANSAÇÕES ENTRE USUÁRIOS E ENTRE USUÁRIOS E TERCEIROS
11.1. A BRIKEBRAK não será responsável pelos negócios e/ou transações, efetivadas ou não, entre Usuários ou entre Usuários e terceiros. Exemplificando, entendem-se como negócios: o pagamento e contratação de bens e serviços e quaisquer outros termos, condições, garantias ou representações associadas a essas transações. Transações são realizadas entre Usuários ou entre Usuários e terceiros, e portanto de sua exclusiva responsabilidade, sem qualquer envolvimento ou participação da BRIKEBRAK.
11.2. O Usuário está ciente de que a BRIKEBRAK não deve ser responsabilizada ou sujeitar-se a quaisquer perdas e/ou danos incorridos em face destas transações. Os Usuários concordam que, em caso de litígio entre Usuários ou entre Usuários e terceiros, a BRIKEBRAK não será, de qualquer forma, envolvida ou responsabilizada.

12. LIMITAÇÃO E TÉRMINO DO SERVIÇO
12.1. O Usuário reconhece que a BRIKEBRAK pode estabelecer limites referentes ao uso e acesso do site, inclusive quanto ao número máximo de dias que um dado será exibido no site, ou outros Dados e/ou Conteúdos que possam ser transmitidos ou armazenados no site.
12.2. O dado aparecerá a partir de sua sua publicação nas ferramentas de busca do site, e não será mais exibido nos resultados da ferramenta de “busca” quando o mecanismo de busca e encontro for acionado (exemplo: oferta de veiculo ou peça versus escolha pelo interessado), entretanto, poderá ser encontrado em listagem de dados antigos, com os dizeres: “finalizado”. O dado também deixará de aparecer na na URL “BRIKEBRAK”.
12.3. O Usuário reconhece que a BRIKEBRAK não é obrigada a manter ou armazenar qualquer Dado e/ou Conteúdo no Site, podendo, a qualquer momento e por qualquer motivo, modificar ou descontinuar o Serviço, sem aviso prévio, e sem que qualquer obrigação seja criada com os Usuários ou com terceiros por tais modificações, suspensões ou descontinuidade do Serviço.
12.4. O Usuário concorda que a BRIKEBRAK, a seu critério, pode excluir ou desativar sua conta, bloquear seu e-mail ou endereço de IP, ou, de outro modo, encerrar seu acesso ou uso do Site (ou parte dele) imediatamente, sem aviso prévio, além de remover qualquer Dado e/ou Conteúdo do site.
12.5. O Usuário reconhece ainda, que a BRIKEBRAK não possui nenhuma obrigação com ele ou com terceiros pelo término de seu acesso ao site e concorda em não tentar acessá-lo novamente.



13. TRANSFERÊNCIA DE DIREITOS
13.1. Estas P&A, bem como quaisquer direitos, licenças e/ou autorizações implícitas ou expressas concedidas pela BRIKEBRAK aos seus Usuários, não podem ser cedidos, ou de qualquer forma transferidos, pelo Usuário.

14. CAPACIDADE DO USUÁRIO EM USAR OS SERVIÇOS OFERECIDOS PELO SITE
14.1. O Usuário, se pessoa física, declara ser maior de 18 anos, menor emancipado, ou possuir a vontade e o consentimento legal, expresso e por escrito, dos pais ou responsável legal e ser plenamente capaz para se vincular a estes P&A, acatar e cumprir com suas disposições.
14.2. O Usuário, sendo pessoa jurídica, o fará na figura do seu representante legal, respeitando as mesmas disposições do item acima.

15. REGRAS GERAIS, LEGISLAÇÃO APLICÁVEL E FORO
15.1. Estes P&A e quaisquer outras políticas divulgadas pela BRIKEBRAK no Site estabelecem o pleno e completo acordo e entendimento entre o Usuário superando e revogando todos e quaisquer entendimentos, propostas, acordos, negociações e discussões havidos anteriormente entre as partes.
15.2. Os P&A e a relação entre as partes são regidos pelas leis da República Federativa do Brasil.
15.3. As partes elegem o Foro da Comarca da Capital do Estado de residência do Usuário como sendo o único competente para dirimir quaisquer litígios e/ou demandas que venham a envolver as Partes em relação ao uso e acesso do Site.
15.4. A incapacidade da BRIKEBRAK em exercer ou fazer cumprir qualquer direito ou cláusula dos P&A não representa uma renúncia desse direito ou cláusula.
15.5. Na hipótese de que qualquer item, termo ou disposição destes P&A vir a ser declarado nulo ou não aplicável, tal nulidade ou inexequibilidade não afetará quaisquer outros itens, termos ou disposições aqui contidos, os quais permanecerão em pleno vigor e efeito.

16. PRODUTOS E SERVIÇOS NÃO PERMITIDOS NA BRIKEBRAK:
Somente poderão ser veiculados na BRIKEBRAK dados de produtos e/ou serviços permitidos pelos Termos de Uso da BRIKEBRAK e pela lei vigente. Os Usuários são responsáveis pelos produtos e serviços oferecidos e devem certificar-se da autenticidade e legalidade de seus dados. A BRIKEBRAK poderá cancelar dados que infrinjam os Termos de Uso de sua plataforma ou a Lei Vigente.
É proibida a publicação de dados com conteúdo ilegal ou que desrespeite normas específicas.
16.1. Qualquer tipo de serviço e produto ilegal/ilícito, ou de proibida comercialização pela legislação brasileira.
16.3. Serviços ou Produtos embargados ou com restrição documentária e/ou de qualquer espécie quanto ao seu uso, exploração ou transferência de titularidade e/ou posse.
O Usuário tem plena ciência de que seus dados de cadastro e/ou dados de acesso serão informados se solicitados por autoridades competentes (polícia, agências reguladoras, ministério público, ordem judicial).

17. POLITICA DE PREÇOS E REAJUSTES:
A BRIKEBRAK poderá aplicar reajustes de preços anuais em seus planos, de forma automática, seguindo indices oficiais do mercado tendo com base o IGP-M ou outro que o venha a substituir em caso de sua extição . Da mesma, forma poderá oferecer promoções, com por exemplo; isenção de taxas por periodos finitos, descontos, etc... Os Usuários que aderirem  ao sistema BRIKEBRAK, utilizando o APP, URL  e um plano pago, concordam com os termos de cobrança e rajustes.
Os valores serão corrigidos na menor periodicidade permitida em lei, de acordo com a variação do índice IGP-M/FGV ou, em caso de extinção, pelo índice que o substitua. 
 Os usuários poderão extinguir seu contrato, a qualquer tempo sem que haja qualquer cobrança adicional (Ex: multa contratual, etc..), entretanto, eventuais ultimas cobranças sempre considerarão meses inteiros; não pró-rata. (Ex: Contrato anual encerrado em 6 meses e 16 dias cobrança para o setimo mes de forma completa com utilização equivalente do plano até o limite mensal).

			
			</pre>
			<?php /*
			<pre>
			CONSIDERAÇÕES
- Provedor:  BRIKEBRAK 
- Domínios: BRIKEBRAK.com.br, BRIKEBRAK.com, BRIKEBRAK.net
- Propriedade da: SAS GERENCIAMENTO DE RISCOS, Rua Cabo Verde, 140 , Vila Olímpia, São Paulo – SP, CEP 04550-080, registrada no CNPJ/MF sob o nº. 14.537.316/0001-21, 
- URL:  www.BRIKEBRAK.com.br. (.com e .net).
A)  Consiste o serviço comercializado pela BRIKEBRAK na disponibilização aos Usuários de internet e Smartphone de uma plataforma para oferta de bens e serviços. Portanto, atua hospedando conteúdo de terceiros postados por seus Usuários (“Usuário(s)”).
B) Assim, o Usuário publica dados no site da BRIKEBRAK com todos os detalhes possíveis, inclusive seus dados pessoais para contato direto, negociação e conclusão da transação, sendo esta última ocorrida fora do ambiente do site BRIKEBRAK (compra e venda).
C) O Usuário que utiliza o site BRIKEBRAK para ofertar, ou ainda encontrar as informações que procura, o faz por sua vontade, conta e risco, sem que a BRIKEBRAK seja responsável pela precisão dos dados especificados pelos Usuários, nem pela qualidade e demais detalhes daquilo que é ofertado. 
A BRIKEBRAK não participa e/ou interfere, de qualquer forma, na negociação e/ou efetivação de quaisquer transações (venda e compra).
A BRIKEBRAK tem como direcionamento, mas não se limitando, o mercado de transporte (ofertas e procuras por caminhões, onibus, utilitários, implementos, suas peças, empresas de serviços, revendas, seguros, e ainda curriculos profissionais).
MODALIDADES:
D) Ofertas bens, serviços e curriculos são pagas mediante planos descritos no site
D.1) Buscas de bens, serviços e curriculos são livres gratuitas pela URL 
E) As taxas cobradas pela BRIKEBRAK fazem referência as demandas dos Usuários no site e APP. Conforme Politica de Uso e Acesso (P&A) tem disponibildade finita e temporal, podendo ser contratados planos que permitem exposição/buscas,  mensal, semestral e anual.
F) A BRIKEBRAK não garante que haja a negociação e conclusão de uma transação, tampouco reembolsará o Usuário em caso de insucesso. Suas taxas em resumo fazem jus ao uso do site (disponibilização de informações).
Modo de utilização (não exaustivo) sequências de utilização:


- OFERTAS E PROCURAS POR CAMINHÕES, ONIBUS, UTILITÁRIOS, IMPLEMENTOS, SUAS PEÇAS, EMPRESAS DE SERVIÇOS, REVENDAS, SEGUROS, E AINDA CURRICULOS PROFISSIONAIS.

1) Via URL, 

2) Cadastrar login, senha, dados e escolha do que pretende ofertar.

3) A oferta via URL  é paga mediante aderência a um plano.

4) Sua opção permanece em disponível no site durante todo período correspondente ao plano escolhido, podendo ser editado quantas vezes necessitar (o espaço ¨alugado¨no site BRIKEBRAK é de controle de conteúdo do comprador do plano durante todo perírodo escolhido). Ex: Venda de veículo em um plano mensal: Realizou negócio em 4 dias, é possivel publicar outra venda entretanto tem-se a restrição (mesma modalidade de escolha ¨publicação de venda de veículo e dados cadastrais).

5) Inspirado o prazo de um plano, sem que haja renovação, as publicações são retiradas automaticamente do SITE.


1. ADESÃO
1.1. Oferece a BRIKEBRAK ao Usuário recursos  (“Serviços”) para o uso da plataforma de dado virtual regido por estas Politicas de Uso e Acesso da BRIKEBRAK (P&A).
1.2. A adesão aos Serviços implica na devida vontade, compreensão, aceitação e vinculação automática do Usuário as P&A. Ao utilizar os Serviços oferecidos, o Usuário concorda em atender a todas e quaisquer diretrizes dispostas nestas P&A.
1.3. Estas P&A poderão sofrer alterações temporaneas, sejam por questões legais ou estratégicas da BRIKEBRAK. O Usuário concorda e reconhece que é de sua única e inteira responsabilidade a verificação periódica destas P&A. A BRIKEBRAK poderá informar, por sua liberalidade, ao Usuário sobre alterações significativas nas P&A através de avisos em seu site.
 1.4. Caso haja objeção a P&A e/ou alterações posteriores desta, ou eventualmente insatisfação com os Serviços oferecidos pela BRIKEBRAK, o Usuário poderá cessar o uso imediatamente.

2. POLÍTICA </pre>
			
				<p>2.1. É de conhecimento do Usuário de que todos os dados
					disponíveis no site são produzidos e disponibilizados por
					terceiros, sem que haja qualquer tipo de acompanhamento e
					verificação prévia da BRIKEBRAK.</p>
				<p>A BRIKEBRAK não Interfere (controla, edita, monitora) e não é, em
					nenhuma hipótese, responsável pelos dados fornecidos ou qualquer
					outro material disponibilizado ou não através dos Dados submetidos
					ao site por seus Usuários.</p>
				<p>Excessão: publicões que envolverem imagens podem ser submetidas a
					vistoria rápida da equipe BRIKEBRAK afim de evitar-se que conteúdos
					impróprios (pornograficos, ofensivos, ilegais) sejam publicados,
					entretanto, não há edição do anuncio por esta última. Existindo
					eventuais ocorrencias, é iniciado contato com o publicante para que
					este efetue correções.</p>
				<p>O Usuário concorda que ao utilizar o site poderá se expor a
					conteúdo eventualmente, inexato, enganoso ou censurável.</p>
				<p>2.1.1. Concorda o Usuário que deve avaliar e assumir os riscos
					associados a ao Conteúdo e/ou Dado submetido ao site. Em nenhuma
					circunstância, a BRIKEBRAK será responsável, pelo Conteúdo e/ou
					pelas perdas ou danos incorridos em função do uso, submissão e
					acesso de qualquer Conteúdo e/ou Dado listado, enviados ou
					disponibilizados através do site.</p>
				<p>2.1.2. O Usuário reconhece que a BRIKEBRAK terá o direito de, a
					seu exclusivo critério, recusar, excluir ou mover qualquer Conteúdo
					e/ou Dado disponibilizado no site, seja por violação as P&amp;A ou
					por quaisquer outras razões de ordem ética, econômica, legal ou
					moral.</p>
				<p>2.2. O Usuário é o único responsável por todo o Dado e/ou
					Conteúdo de sua autoria ou por ele divulgado, transmitido ou
					associado a link disponibilizado no/ou através do site; assim como
					pelo seu uso, divulgação ou publicação, devendo o Usuário manter a
					BRIKEBRAK, seus funcionários, parceiros e controladores livres e
					indenes de toda e qualquer consequência advinda de seus atos/
					omissões, inclusive em relação a terceiros.</p>
				<p>2.2.1. Com relação ao Dado e/ou Conteúdo divulgado, transmitido
					ou associado a link no Site, o Usuário declara que:</p>
				<p>(i) é o titular dos direitos e/ou possui as autorizações e
					vontades necessárias para divulgar o Conteúdo e permitir que a
					BRIKEBRAK o utilize e/ou eventualmente o formate para melhor
					disposição no Site, e;</p>
				<p>(ii) tem o consentimento expresso por vontade, licença e/ou
					permissão de toda e qualquer pessoa identificável no Conteúdo, seja
					ela para usar seu nome e/ou sua imagem.</p>
				<p>2.3. A BRIKEBRAK não exerce influência para ratificar, editar,
					aprovar ou monitorar previamente qualquer Dado/Conteúdo expresso no
					Site e não assume quaisquer responsabilidades a eles relacionadas.</p>
				<p>2.3.1. O Usuário desde já aceita e concorda que não é permitida
					pela BRIKEBRAK, a submissão ao Site Dados e/ou Conteúdos de
					qualquer forma relacionados a atividades que desrespeitem direitos
					de propriedade intelectual, ou qualquer outra violação a direitos
					de terceiros, e poderá remover todo o Dado e/ou Conteúdo
					inadequado, quando devidamente notificada de que o mesmo viola
					direitos de terceiros ou a legislação brasileira.</p>
				<p>2.3.2. A BRIKEBRAK se reserva o direito de remover o Dado e/ou
					qualquer Conteúdo submetido ao Site sem aviso prévio.</p>
				<p>A BRIKEBRAK poderá, a seu exclusivo critério, suspender ou
					cancelar, de qualquer forma que seja, o cadastro e/ou acesso do
					usuário ao site em caso de infração a qualquer das disposições
					destas P&amp;A.</p>
				<p>A BRIKEBRAK também se reserva o direito de decidir, a seu único e
					exclusivo critério, quais Conteúdos e/ou Dados entende como
					inadequados.</p>
				<p>2.4. Existem modalidades de utilização que, a critério exclusivo
					da BRIKEBRAK, são cobradas taxas para postagem de Conteúdo e/ou
					Dado em determinadas áreas do site.</p>
				<p>2.4.1. No caso de remoção de Conteúdo e/ou Dado por desrespeito
					às Condições de Uso da BRIKEBRAK, não serão reembolsadas eventuais
					taxas pagas pelo destaque do dado ou qualquer outro serviço,</p>
				<p>3. POLÍTICA DE CONTEÚDO E PENALIDADES</p>
				<p>3.1. A BRIKEBRAK não permite, e desde já considera como
					inadequado, quaisquer Dados e/ou Conteúdos enquadrados na lista
					abaixo. Desta forma, o Usuário compromete-se a não divulgar, enviar
					por e-mail, ou disponibilizar de qualquer outro modo, Conteúdo e/ou
					Dado:</p>
				<p>
					(a)Ilícito;<br> (b) Protegido por direitos autorais, segredo
					comercial, industrial ou de terceiros; a menos que o Usuário tenha
					permissão do titular de tais direitos para divulgar o Conteúdo e/ou
					Dado;<br> (c) Que inclua informações pessoais ou que permitam a
					identificação de terceiro sem seu expresso consentimento;<br> (d)
					Falso, fraudulento, enganoso<br> 3.1.1. Além disso, o Usuário
					concorda :<br> (a) Em não entrar em contato com qualquer Usuário
					que peça para não ser contatado;<br> (b) Em não obter, guardar,
					divulgar, comercializar e/ou utilizar dados pessoais sobre outros
					Usuários para fins comerciais ou ilícitos;<br> (c ) Em não divulgar
					Conteúdo e/ou Dado que não seja nacional;
				</p>
				<p>4. ACESSO AO SITE</p>
				<p>4.1. A BRIKEBRAK concede ao Usuário autorização (revogável e sem
					aviso prévio, não-exclusiva e limitada), para acessar o Site e
					utilizá-lo de modo pessoal.</p>
				<p>4.2 O uso do Site para além do âmbito de acesso autorizado pela
					BRIKEBRAK implicará na revogação imediata da licença aqui concedida
					sem prejuízo das penalidades legais.</p>
				<p>5. PUBLICIDADE</p>
				<p>5.1. A BRIKEBRAK oferece a seus Usuários serviços pagos regulares
					denominados PUBLICIDADE que possibilita ao Usuário dar maior
					visibilidade ao seu Dado, mediante pagamento de um valor
					determinado.</p>
				<p>5.1.1. A BRIKEBRAK utiliza os serviços da XXXXXXX
					(www.dinheiromail.com.br) para processar o pagamento do valores dos
					planos e, por tanto, será necessário cadastro junto ao mesmo.</p>
				<p>5.1.1.1. O Usuário aceita e concorda que a XXXXXXX, ou qualquer
					outro provedor de serviços online eventualmente utilizado para
					processar estes pagamentos, atua por sua única e exclusiva
					responsabilidade e o Usuário está ciente de que esta transação será
					regida pelos termos de uso aceitos no momento do cadastro junto a
					este provedor.</p>
				<p>5.1.1.2. O Usuário aceita e concorda que a BRIKEBRAK é alheia a
					esta transação e não responderá, sob qualquer hipótese, pela
					segurança e qualidade desta.</p>
				<p>
					5.1.2. Este valor pago não será, em qualquer hipótese, reembolsado
					pela BRIKEBRAK.<br> 5.2. A BRIKEBRAK não garante qualquer resultado
					relacionado ao PUBLICIDADE.
				</p>
				<p>6. NOTIFICAÇÃO SOBRE INFRAÇÕES</p>
				<p>6.1. Caso qualquer pessoa, Usuário ou não, se sentir lesado em
					relação a qualquer Dado e/ou Conteúdo, poderá encaminhar à
					BRIKEBRAK notificação por escrito solicitando sua retirada. Email:
					atendimento@brikebrak.com.br. No entanto, para não prejudicar
					Usuários de boa-fé, a retirada do Dado e/ou Conteúdo do Site pela
					BRIKEBRAK será dependente de efetiva comprovação ou forte evidência
					da ilegalidade ou infração à lei, direitos de terceiros e/ou aos
					P&amp;A.</p>
				<p>6.3. As notificações deverão ainda conter as seguintes
					informações:</p>
				<p>
					a) Assinatura física ou eletrônica da pessoa supostamente lesada,
					ou, se for o caso, do titular do direito intelectual violado;<br>
					b) Identificação do objeto protegido por direitos intelectuais que
					tenha sido violado, se for o caso;<br> c) Identificação do material
					que supostamente representa a infração, código do(s) Dado(s) e/ou
					link do(s) Dado(s), ou, em caso de não se tratarem de Dados,
					informações necessárias para a devida identificação do Conteúdo;<br>
					d) Declaração de que o notificante possui elementos suficientes
					para embasar a alegação de violação legal; e<br> e )Declaração de
					que as informações contidas na notificação são precisas e
					verdadeiras, sob pena de incorrer nas consequentes
					responsabilidades cíveis e penais, e de que o notificante está
					autorizado a agir em nome do titular do direito supostamente
					violado.<br> 6.4. As notificações deverão ser encaminhadas à
					BRIKEBRAK através de email. Apenas as notificações relacionadas a
					efetiva violação de direitos devem ser encaminhados.<br> Quaisquer
					naturezas de opinião como, comentários, sugestões, críticas,
					solicitações de suporte técnico e outras comunicações devem ser
					direcionadas ao atendimento ao cliente da BRIKEBRAK clicando no
					LINK “FALE CONOSCO” no site.
				</p>
				<p>7. POLÍTICA DE PRIVACIDADE E DIVULGAÇÃO DE INFORMAÇÕES</p>
				<p>7.1. O Usuário desde já autoriza a BRIKEBRAK a, preservar,
					armazenar todos os Dados e/ou Conteúdos submetidos ao site, bem
					como todos os seus dados pessoais, a exemplo de endereços de
					e-mail, endereços de IP (Internet Protocol), informações de data e
					horário de acesso, entre outras informações. O Usuário também
					autoriza a BRIKEBRAK a informar e/ou divulgar estes dados em caso
					de exigência legal ou se razoavelmente necessárias para: cumprir
					com o devido processo legal; fazer cumprir estes P&amp;A; responder
					a alegações de suposta violação de direitos de terceiros e de
					divulgação indevida de informações para contato de terceiros (por
					exemplo, número de telefone, endereço residencial), e para proteger
					os direitos, a propriedade ou a segurança de terceiros ou da
					própria BRIKEBRAK e de seus Usuários.</p>
				<p>7.2. A BRIKEBRAK poderá utilizar empresas de processamento de
					cartões de crédito e/ou de gestão de meios de pagamentos online
					terceirizadas, assim como empresas para monitorar o tráfego do
					Site, que, em alguns casos, poderão armazenar e coletar informações
					e dados do Usuário.</p>
				<p>7.3. A utilização do Site implica no consentimento do Usuário
					para coleta, armazenamento e uso das informações pessoais
					fornecidas e suas atualizações, dados de tráfego, endereços IP,
					entre outros.</p>
				<p>7.4. A BRIKEBRAK poderá utilizar cookies para administrar as
					sessões dos Usuários e armazenar preferências, rastrear
					informações, idioma selecionado, entre outros. Cookies poderão ser
					utilizados independentemente de cadastro do Usuário.</p>
				<p>7.4.1. Em alguns casos, prestadores de serviços terceirizados
					poderão utilizar cookies no Site, que a BRIKEBRAK não controla nem
					acessa. Tais cookies não são regulados por estes Termos e
					Condições.</p>
				<p>7.5. O Usuário tem a opção de aceitar ou recusar o uso de cookies
					em seu computador, independente de cadastro no Site, configurando
					seu navegador como desejar. A recusa do uso de cookies pode,
					contudo, resultar na limitação do acesso do Usuário a certas
					ferramentas disponíveis no Site, dificuldades no login, uso do
					Fórum BRIKEBRAK e na ferramenta de comentários.</p>
				<p>7.6. Considerando que a BRIKEBRAK poderá realizar parcerias com
					terceiros, eventualmente estes poderão coletar informações de
					Usuários como endereço IP, especificação do navegador e sistema
					operacional. Estes Termos e Condições não se aplicam às informações
					pessoais fornecidas aos terceiros e por eles armazenadas e
					utilizadas.</p>
				<p>7.7. O Site poderá, eventualmente, conter links para sites de
					terceiros. A BRIKEBRAK não se responsabiliza pelo conteúdo ou pela
					segurança das informações do Usuário quando acessar sites de
					terceiros. Tais sites podem possuir suas próprias políticas de
					privacidade quanto ao armazenamento e conservação de informações
					pessoais, completamente alheias à BRIKEBRAK.</p>
				<p>7.8. A BRIKEBRAK poderá trabalhar com empresas terceirizadas de
					propaganda para a divulgação de dados durante visitas a seu site.
					Tais empresas poderão coletar informações sobre as visitas de
					Usuários ao site da BRIKEBRAK, no intuito de fornecer dados
					personalizados sobre bens e serviços do interesse do Usuário. Tais
					informações não incluem nem incluirão nome, endereço, e-mail ou
					número de telefone do Usuário.</p>
				<p>7.8.1. No site da BRIKEBRAK, fornecedores terceirizados poderão
					utilizar cookies para divulgar dados relacionados com os Dados e/ou
					Conteúdos. O uso de cookies DART permite a divulgação de dados aos
					Usuários com base em suas visitas ao site da BRIKEBRAK e a outros
					websites.</p>
				<p>7.9. Ao publicar um dado na BRIKEBRAK, o Usuário compreende que
					os dados e o Conteúdo são públicos e acessíveis a terceiros,
					podendo ser listados nos resultados de ferramentas de pesquisa
					disponiveis na WEB e outros e no cache dessas ferramentas de
					pesquisa, em feeds e outros websites por acordos comerciais entre a
					BRIKEBRAK e outras prestadoras de serviço.</p>
				<p>O Usuário compreende que é de responsabilidade de cada uma dessas
					ferramentas de pesquisa, websites ou recursos RSS manter seus
					índices e cache atualizados e remover o Conteúdo de seus índices e
					cache, pois não é possível que a BRIKEBRAK exerça influência sobre
					eles.</p>
				<p>7.10. A BRIKEBRAK poderá utilizar as informações e/ou dados
					fornecidos e/ou coletados pelo Usuário para:</p>
				<p>
					(i) Aplicar estes P&amp;A;<br> (ii) Acompanhar as atividades do
					Usuário, utilizando palavras chave de pesquisas e novos dados para
					administrar mais efetivamente o tráfego no Site;<br> (ii) Prestar
					serviços ao Usuário;<br> (iv) Criar e administrar Contas de
					Usuário; e<br> (v) Prestar assistência.
				</p>
				<p>7.11. A BRIKEBRAK poderá, ainda, compartilhar informações
					coletadas, como a capacidade do navegador ou o sistema operacional
					do Usuário, com os prestadores de serviços terceirizados, no
					intuito de compreender melhor quais dados e serviços podem ser de
					interesse do Usuário.</p>
				<p>7.12. É reservado à BRIKEBRAK o direito de bloquear o acesso ao
					Site de Usuários alocados em outros países.</p>
				<p>7.13. A BRIKEBRAK se reserva o direito de reter informações pelo
					período que entender necessário para o bom cumprimento de seus
					negócios, mesmo após o encerramento da conta do Usuário, salvo
					manifestação expressa do Usuário em sentido contrário.</p>
				<p>7.14. A BRIKEBRAK não processa pagamentos diretamente e não
					armazena informações de cartões de crédito dos Usuários. É
					utilizada a tecnologia “secured socket layer” (SSL) para o
					processamento de transações com prestadores de serviços
					terceirizados.</p>
				<p>7.15. As informações e dados cadastrais do Usuário podem ser
					protegidas por senha e nome de Usuário exclusivos, pessoais e
					intransferíveis, que não devem ser divulgadas, quer pela BRIKEBRAK,
					quer pelo próprio Usuário.</p>
				<p>7.16. As informações referentes ao Serviço são mantidas em uma
					base de dados localizada no Brasil e eventualmente em outros
					paises.</p>
				<p>7.17. O Usuário desde já declara estar ciente que a BRIKEBRAK não
					assume nenhuma responsabilidade em caso de roubo, perda, alteração
					ou uso indevido de suas informações pessoais e do Conteúdo como um
					todo, inclusive na hipótese de informações fornecidas a prestadores
					de serviços terceirizados ou a outros Usuários e na hipótese de
					descumprimento destes P&amp;A por prestadores de serviços
					terceirizados.</p>
				<p>7.18. Participação no SITE BRIKEBRAK ou utilização da ferramenta
					de Comentários.</p>
				<p>7.18.1. O Nome de Usuário do Usuário será divulgado em suas
					postagens no SITE.</p>
				<p>7.18.2. O nome e e-mail do Usuário somente serão divulgados em
					seus comentários quando neles inclusos pelo próprio Usuário.</p>
				<p>7.18.3. A BRIKEBRAK recomenda que o Usuário não divulgue nestas
					ferramentas, ou em qualquer outro Conteúdo, informações que o
					Usuário não deseja que sejam públicas.</p>
				<p>7.19. O Usuário não precisa se cadastrar para postar ou responder
					a Dados no Site. Ao utilizar o site da BRIKEBRAK para postar ou
					responder dados o Usuário manifesta aceite aos Politica de Uso
					BRIKEBRAK, a BRIKEBRAK poderá enviar ao Usuário notificações sobre
					dados, promoções, conteúdos especiais e notificações, exigidas
					legalmente ou não.</p>
				<p>7.19.1. O Usuário poderá optar por não receber via e-mail
					determinadas mensagens, como newsletters, recomendações de compra e
					venda no Site, avisos de recebimento de comentários em seus dados e
					avisos de autorização para atualização de suas mensagens. Tais
					preferências não serão alteradas sem o devido consentimento do
					Usuário.</p>
				<p>8. DIREITOS DE PROPRIEDADE INTELECTUAL</p>
				<p>8.1. Os elementos e/ou ferramentas encontrados no site, com
					exceção dos Conteúdos e/ou Dados submetidos por Usuários são de
					titularidade ou licenciados pela BRIKEBRAK, sujeitos aos direitos
					intelectuais de acordo com as leis brasileiras e tratados e
					convenções internacionais dos quais o Brasil seja signatário.
					Apenas a título exemplificativo, entendem-se como tais: textos,
					softwares, scripts, imagens gráficas, fotos, sons, músicas, vídeos,
					recursos interativos e similares, marcas, marcas de serviços,
					logotipos e “look and feel”.</p>
				<p>8.2. Os elementos e/ou ferramentas que são disponibilizados para
					o Usuário no site os são tão e somente no ESTADO EM QUE SE
					ENCONTRAM e apenas para sua informação e uso pessoal na forma
					designada pela BRIKEBRAK. Tais elementos e/ou ferramentas não podem
					ser usados, copiados, reproduzidos, distribuídos, transmitidos,
					difundidos, exibidos, vendidos, licenciados ou, de outro modo,
					explorados para quaisquer fins, sem o consentimento prévio e por
					escrito da BRIKEBRAK.</p>
				<p>8.3. A BRIKEBRAK reserva a si todos os direitos que não foram
					expressamente previstos em relação ao Site, aos seus elementos e/ou
					ferramentas. O Usuário compromete-se a não usar, reproduzir ou
					distribuir quaisquer elementos e/ou ferramentas que não sejam
					expressamente permitidos pela BRIKEBRAK – inclusive o uso,
					reprodução ou distribuição para fins comerciais dos Dados e/ou
					Conteúdos extraídos do site. Caso o Usuário faça qualquer cópia,
					seja ela via download ou impressão, dos elementos e/ou ferramentas
					da BRIKEBRAK para uso exclusivamente pessoal, deverá preservar
					todos os direitos de propriedade intelectual inerentes. O Usuário
					concorda em não burlar, desativar ou, de alguma forma, interferir
					em recursos e/ou ferramentas relacionados à segurança do site, sob
					pena de incorrer nas medidas judiciais cabíveis.</p>
				<p>9. GARANTIA DE DADO E/OU CONTEÚDO</p>
				<p>9.1. O Usuário está ciente de que, ao acessar o Site da
					BRIKEBRAK, (i) estará exposto a Dados e/ou Conteúdos de uma
					variedade de fontes não validadas ou garantidas previamente pela
					BRIKEBRAK, e (ii) que a BRIKEBRAK não é responsável pela sua
					precisão, veracidade, legalidade, licitude, utilidade e/ou
					segurança destes Dados e/ou Conteúdos.</p>
				<p>9.2. A BRIKEBRAK também não garante o sucesso nas transações ou
					informações buscadas no site, na forma descrita no item 10 adiante.</p>
				<p>10. LIMITAÇÃO DE RESPONSABILIDADE</p>
				<p>O Usuário se compromete a defender, indenizar e isentar de
					qualquer responsabilidade a BRIKEBRAK, seus executivos,
					subsidiárias, afiliados, sucessores, prepostos, diretores, agentes,
					prestadores de serviços, fornecedores e funcionários com relação a
					toda e qualquer reclamação, perda, dano, obrigação, custos, dívidas
					ou despesas (incluindo, entre outros, honorários advocatícios e
					custas processuais) incorridas em razão de: (i) mau uso e acesso do
					Site da BRIKEBRAK; (ii) violação e/ou não observância de quaisquer
					dispositivos destes P&amp;A; (iii) violação de qualquer direito de
					terceiros, incluindo, mas sem se limitar a, qualquer direito
					proprietário ou de privacidade; ou (iv) qualquer reclamação de que
					algum Dado e/ou Conteúdo causou dano a terceiros. Esta defesa e
					obrigação de indenização subsistirão a estes P&amp;A e ao uso e/ou
					acesso do site.</p>
				<p>11. TRANSAÇÕES ENTRE USUÁRIOS E ENTRE USUÁRIOS E TERCEIROS</p>
				<p>11.1. A BRIKEBRAK não será responsável pelos negócios e/ou
					transações, efetivadas ou não, entre Usuários ou entre Usuários e
					terceiros. Exemplificando, entendem-se como negócios: o pagamento e
					contratação de bens e serviços e quaisquer outros termos,
					condições, garantias ou representações associadas a essas
					transações. Transações são realizadas entre Usuários ou entre
					Usuários e terceiros, e portanto de sua exclusiva responsabilidade,
					sem qualquer envolvimento ou participação da BRIKEBRAK.</p>
				<p>11.2. O Usuário está ciente de que a BRIKEBRAK não deve ser
					responsabilizada ou sujeitar-se a quaisquer perdas e/ou danos
					incorridos em face destas transações. Os Usuários concordam que, em
					caso de litígio entre Usuários ou entre Usuários e terceiros, a
					BRIKEBRAK não será, de qualquer forma, envolvida ou
					responsabilizada.</p>
				<p>12. LIMITAÇÃO E TÉRMINO DO SERVIÇO</p>
				<p>12.1. O Usuário reconhece que a BRIKEBRAK pode estabelecer
					limites referentes ao uso e acesso do site, inclusive quanto ao
					número máximo de dias que um dado será exibido no site, ou outros
					Dados e/ou Conteúdos que possam ser transmitidos ou armazenados no
					site.</p>
				<p>12.2. O dado aparecerá a partir de sua sua publicação nas
					ferramentas de busca do site, e não será mais exibido nos
					resultados da ferramenta de “busca” quando o mecanismo de busca e
					encontro for acionado (exemplo: oferta de veiculo ou peça versus
					escolha pelo interessado), entretanto, poderá ser encontrado em
					listagem de dados antigos, com os dizeres: “finalizado”. O dado
					também deixará de aparecer na na URL “BRIKEBRAK”.</p>
				<p>12.3. O Usuário reconhece que a BRIKEBRAK não é obrigada a manter
					ou armazenar qualquer Dado e/ou Conteúdo no Site, podendo, a
					qualquer momento e por qualquer motivo, modificar ou descontinuar o
					Serviço, sem aviso prévio, e sem que qualquer obrigação seja criada
					com os Usuários ou com terceiros por tais modificações, suspensões
					ou descontinuidade do Serviço.</p>
				<p>12.4. O Usuário concorda que a BRIKEBRAK, a seu critério, pode
					excluir ou desativar sua conta, bloquear seu e-mail ou endereço de
					IP, ou, de outro modo, encerrar seu acesso ou uso do Site (ou parte
					dele) imediatamente, sem aviso prévio, além de remover qualquer
					Dado e/ou Conteúdo do site.</p>
				<p>12.5. O Usuário reconhece ainda, que a BRIKEBRAK não possui
					nenhuma obrigação com ele ou com terceiros pelo término de seu
					acesso ao site e concorda em não tentar acessá-lo novamente.</p>
				<p>13. TRANSFERÊNCIA DE DIREITOS</p>
				<p>13.1. Estas P&amp;A, bem como quaisquer direitos, licenças e/ou
					autorizações implícitas ou expressas concedidas pela BRIKEBRAK aos
					seus Usuários, não podem ser cedidos, ou de qualquer forma
					transferidos, pelo Usuário.</p>
				<p>14. CAPACIDADE DO USUÁRIO EM USAR OS SERVIÇOS OFERECIDOS PELO
					SITE</p>
				<p>14.1. O Usuário, se pessoa física, declara ser maior de 18 anos,
					menor emancipado, ou possuir a vontade e o consentimento legal,
					expresso e por escrito, dos pais ou responsável legal e ser
					plenamente capaz para se vincular a estes P&amp;A, acatar e cumprir
					com suas disposições.</p>
				<p>14.2. O Usuário, sendo pessoa jurídica, o fará na figura do seu
					representante legal, respeitando as mesmas disposições do item
					acima.</p>
				<p>15. REGRAS GERAIS, LEGISLAÇÃO APLICÁVEL E FORO</p>
				<p>15.1. Estes P&amp;A e quaisquer outras políticas divulgadas pela
					BRIKEBRAK no Site estabelecem o pleno e completo acordo e
					entendimento entre o Usuário superando e revogando todos e
					quaisquer entendimentos, propostas, acordos, negociações e
					discussões havidos anteriormente entre as partes.</p>
				<p>15.2. Os P&amp;A e a relação entre as partes são regidos pelas
					leis da República Federativa do Brasil.</p>
				<p>15.3. As partes elegem o Foro da Comarca da Capital do Estado de
					residência do Usuário como sendo o único competente para dirimir
					quaisquer litígios e/ou demandas que venham a envolver as Partes em
					relação ao uso e acesso do Site.</p>
				<p>15.4. A incapacidade da BRIKEBRAK em exercer ou fazer cumprir
					qualquer direito ou cláusula dos P&amp;A não representa uma
					renúncia desse direito ou cláusula.</p>
				<p>15.5. Na hipótese de que qualquer item, termo ou disposição
					destes P&amp;A vir a ser declarado nulo ou não aplicável, tal
					nulidade ou inexequibilidade não afetará quaisquer outros itens,
					termos ou disposições aqui contidos, os quais permanecerão em pleno
					vigor e efeito.</p>
				<p>16. PRODUTOS E SERVIÇOS NÃO PERMITIDOS NA BRIKEBRAK:</p>
				<p>Somente poderão ser veiculados na BRIKEBRAK dados de produtos
					e/ou serviços permitidos pelos Termos de Uso da BRIKEBRAK e pela
					lei vigente. Os Usuários são responsáveis pelos produtos e serviços
					oferecidos e devem certificar-se da autenticidade e legalidade de
					seus dados. A BRIKEBRAK poderá cancelar dados que infrinjam os
					Termos de Uso de sua plataforma ou a Lei Vigente.</p>
				<p>É proibida a publicação de dados com conteúdo ilegal ou que
					desrespeite normas específicas.</p>
				<p>16.1. Qualquer tipo de serviço e produto ilegal/ilícito, ou de
					proibida comercialização pela legislação brasileira.</p>
				<p>
					16.3. Serviços ou Produtos embargados ou com restrição documentária
					e/ou de qualquer espécie quanto ao seu uso, exploração ou
					transferência de titularidade e/ou posse.<br> O Usuário tem plena
					ciência de que seus dados de cadastro e/ou dados de acesso serão
					informados se solicitados por autoridades competentes (polícia,
					agências reguladoras, ministério público, ordem judicial).
				</p>
				<p>17. POLITICA DE PREÇOS E REAJUSTES:</p>
				<p>A BRIKEBRAK poderá aplicar reajustes de preços anuais em seus
					planos, de forma automática, seguindo indices oficiais do mercado
					tendo com base o IGP-M ou outro que o venha a substituir em caso de
					sua extição . Da mesma, forma poderá oferecer promoções, com por
					exemplo; isenção de taxas por periodos finitos, descontos, etc...
					Os Usuários que aderirem ao sistema BRIKEBRAK, utilizando o APP,
					URL e um plano pago, concordam com os termos de cobrança e
					rajustes.</p>
				<p>
					Os valores serão corrigidos na menor periodicidade permitida em
					lei, de acordo com a variação do índice IGP-M/FGV ou, em caso de
					extinção, pelo índice que o substitua.<br> Os usuários poderão
					extinguir seu contrato, a qualquer tempo sem que haja qualquer
					cobrança adicional (Ex: multa contratual, etc..), entretanto,
					eventuais ultimas cobranças sempre considerarão meses inteiros; não
					pró-rata. (Ex: Contrato anual encerrado em 6 meses e 16 dias
					cobrança para o setimo mes de forma completa com utilização
					equivalente do plano até o limite mensal).
				</p>*/ ?>
			</div>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
			<div class="col-lg-12">
				<img src="assets/images/PUBLICIDADE.jpg" width="300" height="180"
					alt="" /> <br>
				<br> <img src="assets/images/PUBLICIDADE.jpg" width="300"
					height="180" alt="" />

			</div>
		</div>
	</div>
</div>