<?php 
if($this->zfcUserIdentity() !== null){
    // @todo Verificar autenticação 
    header('Location: /user/login');
}
?>

<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Brik e Brak')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') 
                                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') 
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink()//->prependStylesheet('/dashboard/css/ace.min.css')
                                ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300')
                                ->prependStylesheet('http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css')
                                //->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css')
                                ->prependStylesheet('/dashboard/css/bootstrap.min.css')
                                
                                 ?>

    <!-- Scripts -->
    <?php echo $this->headScript()//->prependFile('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js')
                                  //->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js')
                                  //->prependFile('https://oss.maxcdn.com/respond/1.4.2/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  //->prependFile('https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js',   'text/javascript', array('conditional' => 'lt IE 9',)) 
                                  //->prependFile('http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css',   'text/javascript', array('conditional' => 'lt IE 9',)) 
    ?>

		<!-- ace styles -->
		<link rel="stylesheet" href="/dashboard/css/ace.min.css" class="ace-main-stylesheet" id="main-ace-style" />

		<!--[if lte IE 9]>
			<link rel="stylesheet" href="/dashboard/css/ace-part2.min.css" class="ace-main-stylesheet" />
		<![endif]-->

		<!--[if lte IE 9]>
		  <link rel="stylesheet" href="/dashboard/css/ace-ie.min.css" />
		<![endif]-->

		<!-- inline styles related to this page -->

		<!-- ace settings handler -->
		<script src="/dashboard/js/ace-extra.min.js"></script>

		<!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->

		<!--[if lte IE 8]>
		<script src="/dashboard/js/html5shiv.min.js"></script>
		<script src="/dashboard/js/respond.min.js"></script>
		<![endif]-->
  </head>

  <body class="no-skin">
		<div id="navbar" class="navbar navbar-default">
			<script type="text/javascript">
				try{ace.settings.check('navbar' , 'fixed')}catch(e){}
			</script>

			<div class="navbar-container" id="navbar-container">
				<button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="javascript: void(0);sidebar">
					<span class="sr-only">Toggle sidebar</span>

					<span class="icon-bar"></span>

					<span class="icon-bar"></span>

					<span class="icon-bar"></span>
				</button>

				<div class="navbar-header pull-left">
					<a href="/admin/index" class="navbar-brand">
						<small>
							Brik e Brak Admin
						</small>
					</a>
				</div>
				<div class="navbar-buttons navbar-header pull-right" role="navigation">
					<ul class="nav ace-nav">
						<li class="light-blue">
							<a data-toggle="dropdown" href="javascript: void(0);" class="dropdown-toggle">
								<!-- img class="nav-user-photo" src="/dashboard/avatars/user.jpg" alt="Jason's Photo" /-->
								<?php $attr = array('class' => 'nav-user-photo'); echo $this->gravatar($this->zfcUserIdentity()->getEmail(), NULL,$attr) ?>
								<span class="user-info">
									<small>Olá,</small>
									<?php echo $this->zfcUserIdentity()->getDisplayname(); ?>
								</span>

								<i class="ace-icon fa fa-caret-down"></i>
							</a>

							<ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">

								<li>
									<a href="/user">
										<i class="ace-icon fa fa-user"></i>
										Perfil
									</a>
								</li>

								<li class="divider"></li>

								<li>
									<a href="/user/logout">
										<i class="ace-icon fa fa-power-off"></i>
										Sair
									</a>
								</li>
							</ul>
						</li>
					</ul>
				</div>
			</div><!-- /.navbar-container -->
		</div>

		<div class="main-container" id="main-container">
			<script type="text/javascript">
				try{ace.settings.check('main-container' , 'fixed')}catch(e){}
			</script>

			<div id="sidebar" class="sidebar                  responsive">
				<script type="text/javascript">
					try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
				</script>

				<ul class="nav nav-list">
					<li class="">
						<a href="admin/index">
							<i class="menu-icon fa fa-tachometer"></i>
							<span class="menu-text"> Dashboard </span>
						</a>

						<b class="arrow"></b>
					</li>
					<li class="">
						<a href="<?php echo $this->url('zfcadmin/zfcuseradmin/list'); ?>">
							<i class="menu-icon fa fa-users"></i>
							<span class="menu-text"> Usuários </span>
						</a>

						<b class="arrow"></b>
					</li>
					<li class="">
						<a href="<?php echo $this->url('zfcadmin-list', array( 'entity' => 'advertising')); ?>">
							<i class="menu-icon glyphicon glyphicon-list-alt"></i>
							<span class="menu-text"> Anúncios </span>
						</a>

						<b class="arrow"></b>
					</li>
					<li class="">
						<a href="javascript: void(0);" class="dropdown-toggle">
							<i class="menu-icon fa fa-desktop"></i>
							<span class="menu-text">
								Itens
							</span>

							<b class="arrow fa fa-angle-down"></b>
						</a>

						<b class="arrow"></b>

						<ul class="submenu">
							<li class="">
								<a href="javascript: void(0);" class="dropdown-toggle">
									<i class="menu-icon fa fa-caret-right"></i>
									Caminhões
								</a>

								<b class="arrow fa fa-angle-down"></b>
								
								<ul class="submenu">
        							<li class="">
        								<a href="<?php echo $this->url('zfcadmin-list', array( 'entity' => 'car')); ?>">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Lista
        								</a>
        							</li>
        							<li class="">
        								<a href="<?php echo $this->url('zfcadmin-list', array( 'entity' => 'brand')); ?>">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Marcas
        								</a>
        							</li>
        							<li class="">
        								<a href="<?php echo $this->url('zfcadmin-list', array( 'entity' => 'model')); ?>">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Modelos
        								</a>
        							</li>
        							<li class="">
        								<a href="<?php echo $this->url('zfcadmin-list', array( 'entity' => 'bodywork')); ?>">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Carrocerias
        								</a>
        							</li>
        							<li class="">
        								<a href="javascript: void(0);" class="dropdown-toggle">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Tipos
        								</a>
        							</li>
    							</ul>
							</li>
							<li class="">
								<a href="javascript: void(0);" class="dropdown-toggle">
									<i class="menu-icon fa fa-caret-right"></i>
									Cavalos
								</a>

								<b class="arrow fa fa-angle-down"></b>
								
								<ul class="submenu">
        							<li class="">
        								<a href="<?php echo $this->url('zfcadmin-list', array( 'entity' => 'cart')); ?>">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Lista
        								</a>
        							</li>
        							<li class="">
        								<a href="<?php echo $this->url('zfcadmin-list', array( 'entity' => 'brand')); ?>">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Marcas
        								</a>
        							</li>
        							<li class="">
        								<a href="<?php echo $this->url('zfcadmin-list', array( 'entity' => 'model')); ?>">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Modelos
        								</a>
        							</li>
    							</ul>
							</li>
							<li class="">
								<a href="javascript: void(0);" class="dropdown-toggle">
									<i class="menu-icon fa fa-caret-right"></i>
									Ônibus
								</a>

								<b class="arrow fa fa-angle-down"></b>
								
								<ul class="submenu">
        							<li class="">
        								<a href="javascript: void(0);" class="dropdown-toggle">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Lista
        								</a>
        							</li>
        							<li class="">
        								<a href="<?php echo $this->url('zfcadmin-list', array( 'entity' => 'brand')); ?>">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Marcas
        								</a>
        							</li>
        							<li class="">
        								<a href="<?php echo $this->url('zfcadmin-list', array( 'entity' => 'model')); ?>">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Modelos
        								</a>
        							</li>
        							<li class="">
        								<a href="<?php echo $this->url('zfcadmin-list', array( 'entity' => 'bodywork')); ?>">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Carrocerias
        								</a>
        							</li>
        							<li class="">
        								<a href="javascript: void(0);">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Tipos
        								</a>
        							</li>
        						</ul>
							</li>
							<li class="">
								<a href="javascript: void(0);" class="dropdown-toggle">
									<i class="menu-icon fa fa-caret-right"></i>
									Utilitários/Vans
								</a>

								<b class="arrow fa fa-angle-down"></b>
								
								<ul class="submenu">
        							<li class="">
        								<a href="javascript: void(0);">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Lista
        								</a>
        							</li>
        							<li class="">
        							<a href="<?php echo $this->url('zfcadmin-list', array( 'entity' => 'brand')); ?>">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Marcas
        								</a>
        							</li>
        							<li class="">
        								<a href="<?php echo $this->url('zfcadmin-list', array( 'entity' => 'model')); ?>">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Modelos
        								</a>
        							</li>
        						</ul>
							</li>
							<li class="">
								<a href="javascript: void(0);" class="dropdown-toggle">
									<i class="menu-icon fa fa-caret-right"></i>
									Carretas/Implementos
								</a>

								<b class="arrow fa fa-angle-down"></b>
								
								<ul class="submenu">
        							<li class="">
        								<a href="javascript: void(0);">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Lista
        								</a>
        							</li>
        							<li class="">
        								<a href="<?php echo $this->url('zfcadmin-list', array( 'entity' => 'brand')); ?>">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Marcas
        								</a>
        							</li>
        							<li class="">
        								<a href="<?php echo $this->url('zfcadmin-list', array( 'entity' => 'model')); ?>">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Modelos
        								</a>
        							</li>
        							<li class="">
        								<a href="<?php echo $this->url('zfcadmin-list', array( 'entity' => 'bodywork')); ?>">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Carrocerias
        								</a>
        							</li>
        							<li class="">
        								<a href="javascript: void(0);">
        									<i class="menu-icon fa fa-caret-right"></i>
        									Eixos
        								</a>
        							</li>
        						</ul>
							</li>
							<li class="">
								<a href="javascript: void(0);" class="dropdown-toggle">
									<i class="menu-icon fa fa-caret-right"></i>
									Acessórios
								</a>
							</li>
							<li class="">
								<a href="javascript: void(0);" class="dropdown-toggle">
									<i class="menu-icon fa fa-caret-right"></i>
									Insumos e Peças
								</a>
							</li>
						</ul>
					</li>
				</ul><!-- /.nav-list -->

				<script type="text/javascript">
					try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
				</script>
			</div>

			<div class="main-content">
				<div class="main-content-inner">
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<!-- <ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="javascript: void(0);">Home</a>
							</li>

							<li>
								<a href="javascript: void(0);">Other Pages</a>
							</li>
							<li class="active">Blank Page</li>
						</ul><!-- /.breadcrumb -->
						<?php echo $this->navigation()->breadcrumbs(); ?>
					</div>

					<div class="page-content">
						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
                                <?php echo $this->content; ?>
								<!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->
				</div>
			</div><!-- /.main-content -->

			<div class="footer">
				<div class="footer-inner">
					<div class="footer-content">
						<span class="bigger-120">
						    <p>&copy; BRIK e BRAK <?php echo date('Y') ?> | Todos os direitos reservados.</p>
						</span>
					</div>
				</div>
			</div>

			<a href="javascript: void(0);" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
			</a>
		</div><!-- /.main-container -->

		<!-- basic scripts -->

		<!--[if !IE]> -->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

		<!-- <![endif]-->

		<!--[if IE]>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<![endif]-->

		<!--[if !IE]> -->
		<script type="text/javascript">
			window.jQuery || document.write("<script src='/dashboard/js/jquery.min.js'>"+"<"+"/script>");
		</script>

		<!-- <![endif]-->

		<!--[if IE]>
<script type="text/javascript">
 window.jQuery || document.write("<script src='/dashboard/js/jquery1x.min.js'>"+"<"+"/script>");
</script>
<![endif]-->
		<script type="text/javascript">
			if('ontouchstart' in document.documentElement) document.write("<script src='/dashboard/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
		</script>
		<script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

		<!-- page specific plugin scripts -->

		<!-- ace scripts -->
		<script src="/dashboard/js/ace-elements.min.js"></script>
		<script src="/dashboard/js/ace.min.js"></script>

		<!-- inline scripts related to this page -->
		
		<?php echo $this->inlineScript() ?>
	</body>
</html>