<?php echo $this->doctype(); ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Brik e Brak')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/css/style.css')
                        //->prependStylesheet($this->basePath() . '/assets/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.min.css') 
                        ->prependStylesheet('http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css')?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/assets/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/assets/js/jquery.min.js')
            ->prependFile($this->basePath() . '/assets/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/assets/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <!-- SOCIAL BAR -->
			<div class="container-fluid headerSocialBar">
				<div class="container">
					<div class="row">
						<div class="hidden-xs col-sm-7 col-md-7 col-lg-4 col-lg-offset-4">
							<!-- YOUTUBE -->
							<div class="yt-subscribe">
								<div class="g-ytsubscribe" data-channel="GoogleDevelopers"></div>
							</div>
							<!-- FACEBOOK -->
							<div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-width="150" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
						</div>
						<div class="col-xs-12 col-sm-5 col-md-5 col-lg-4">
							<ul>
							<?php
							    if($this->zfcUserIdentity() == null){
                                    // @todo Verificar autenticação 
							        echo '<li><a href="/user">Login</a></li>';
							    } else {
							        echo '<li><a href="' . $this->url('zfcadmin') . '">Admin</a></li>';
							        echo '<li>|</li>';
							        echo '<li><a href="' . $this->url('zfcuser') . '">Perfil</a></li>';
							        echo '<li>|</li>';
							        echo '<li><a href="' . $this->url('zfcuser/logout') . '">Sair</a></li>';
							    } ?>
								
								<li>|</li>
								<li><a href="/atendimento">Atendimento</a></li>
								<li>|</li>
								<li><a href="#">Mapa do Site</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>

			<!-- HEADER -->
			<header class="container-fluid headerLogo">
				<div class="container">
					<div class="row">
						<div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
							<a href="/" title="BrikBrak" class="logo"><img src="/assets/images/logo.png" class="img-responsive"></a>
						</div>
						<div class="hidden-xs col-sm-7 col-md-7 col-lg-7">
						<a href="#"><img src="/assets/images/592x90.png" class="img-responsive pull-right"></a>
						</div>
					</div>
				</div>
			</header>

			<!-- MENU -->
			<div class="container-fluid headerMenu">
				<div class="container">
					<div class="row">
						<nav class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
							<ul class="hidden-xs">
								<li><a href="/servicos">Serviços</a></li>
								<li><a href="/revenda">Revenda</a></li>
								<li><a href="/monitoramento">Monitoramento</a></li>
								<li><a href="/rastreadores">Rastreadores</a></li>
							</ul>
							<select class="visible-xs">
								<option value="/servicos">Serviços</option>
								<option value="/revenda">revenda</option>
								<option value="/monitoramento">monitoramento</option>
								<option value="/rastreadores">rastreadores</option>
								<option value="/profissionais">profissionais</option>
							</select>
						</nav>
						<div class="hidden-xs col-sm-4 col-md-4 col-lg-4">
							<a href="/profissionais" title="Profisisonais" class="btnProfissionais"><span class="icon"></span>Profissionais</a>
						</div>
					</div>
				</div>
			</div>

			<!-- CONTENT -->
			<div class="container-fluid">
				<div class="container">
            	<?php echo $this->content; ?>
            	</div>
			</div>
            <!-- FOOTER -->
			<footer class="container-fluid">
				<div class="container">
					<div clas="row">
						<section class="col-xs-12 col-sm-4 col-md-4 col-lg-2">
							<h1>INSTITUCIONAL</h1>
							<ul>
								<li><a href="/quem-somos">Quem Somos</a></li>
								<li><a href="#">Publicidade</a></li>
								<li><a href="/imprensa">Imprensa</a></li>
								<li><a href="/politica-privacidade">Política de Privacidade</a></li>
								<li><a href="#">Termos de Uso</a></li>
								<li><a href="#">Cód. Defesa Consumidor</a></li>
							</ul>
						</section>
						<section class="col-sx-12 col-sm-4 col-md-4 col-lg-2">
							<h1>MAPA DO SITE</h1>
							<ul>
								<!--li><a href="#">Comprar</a></li>
								<li><a href="#">Vender</a></li>
								<li><a href="#">Financiar</a></li>
								<li><a href="#">Seguro</a></li>
								<li><a href="#">Revista</a></li-->
								<li><a href="/servicos">Serviços</a></li>
								<li><a href="/atendimento">Atendimento</a></li>
								<li><a href="/revenda">Central do Revendedor</a></li>
								<!--li><a href="#">Minha Webmotors</a></li-->
							</ul>
						</section>
						<section class="col-xs-12 col-sm-4 col-md-4 col-lg-3">
							<h1>ATENDIMENTO</h1>
							<ul>
								<li><a href="/atendimento">Fale Conosco</a></li>
								<li><a href="/duvidas-gerais">Dúvidas Gerais</a></li>
								<!--li><a href="#">Como comprar o seu veículo</a></li>
								<li><a href="#">Como vender o seu veículo</a></li>
								<li><a href="#">Anúncios para pessoa jurídica</a></li-->
							</ul>
						</section>
					</div>
					<div class="clearfix"></div>
					<hr>
					<div class="row">
						<div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
							<p class="copyright">&copy; BRIK e BRAK 2014 | Todos os direitos reservados</p>
						</div>
						<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
							<a href="#" title="Agência" class="pull-right"><img src="/assets/images/agencia.png" alt="Agência"></a>
						</div>
					</div>
				</div>
			</footer>
			
			<!-- jQuery -->
			<script src="/assets/js/jquery.min.js"></script>
			<!-- Bootstrap JavaScript -->
			<script src="/assets/js/bootstrap.min.js"></script>
			<!-- Youtube API -->
			<script src="https://apis.google.com/js/platform.js"></script>
			<!-- Enquire -->
			<script src="/assets/js/enquire.min.js"></script>
			<!-- Default -->
			<script src="/assets/js/default.js"></script>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
