<?php 
function getFileList($dir)
{
    // array to hold return value
    $retval = array();

    // add trailing slash if missing
    if(substr($dir, -1) != "/") $dir .= "/";

    // open directory for reading
    $d = new DirectoryIterator($dir) or die("getFileList: Failed opening directory $dir for reading");
    foreach($d as $fileinfo) {
        // skip hidden files
        if($fileinfo->isDot()) continue;
        $retval[] = array(
            'name' => "{$dir}{$fileinfo}",
            'type' => ($fileinfo->getType() == "dir") ? "dir" : mime_content_type($fileinfo->getRealPath()),
            'size' => $fileinfo->getSize(),
            'lastmod' => $fileinfo->getMTime()
        );
    }

    return $retval;
}
?>
<!-- page specific plugin styles -->
		<link rel="stylesheet" href="/dashboard/css/bootstrap-duallistbox.min.css" />
		<link rel="stylesheet" href="/dashboard/css/bootstrap-multiselect.min.css" />
		<link rel="stylesheet" href="/dashboard/css/select2.min.css" />

<?php echo $this->form()->openTag($form) ?>
    <div class="control-group">
        <?php foreach ($form as $element): ?>
            <?php $isButton = $element instanceof Zend\Form\Element\Button; ?>
            <?php $isCheckbox = $element instanceof Zend\Form\Element\Checkbox || $element->getAttribute('type') == 'checkbox'; ?>
            <?php if ($element->getLabel() != null && !$isButton): ?>
                <div><?php echo $this->formLabel($element) ?></div>
            <?php endif ?>
            <?php if ($isButton): ?>
                <div><?php echo $this->formButton($element) ?></div>
            <?php elseif ($element instanceof DoctrineModule\Form\Element\ObjectMultiCheckbox): ?>
                <div class="ckeckbox"><?php echo $this->formMultiCheckbox($element) . $this->formElementErrors($element) ?></div>
            <?php elseif ($element instanceof DoctrineModule\Form\Element\ObjectSelect): ?>
                <div class="select"><?php echo $this->formSelect($element) . $this->formElementErrors($element) ?></div>
            <?php elseif ($element instanceof Zend\Form\Element\Textarea): ?>
                <div class="textarea"><?php echo $this->formTextarea($element) . $this->formElementErrors($element) ?></div>
            <?php elseif ($element instanceof Zend\Form\Element\Radio): ?>
                <div class="radio"><?php echo $this->formRadio($element) . $this->formElementErrors($element) ?></div>
            <?php elseif ($element instanceof Zend\Form\Element\File): ?>
                <div class="form-group">
                <?php if($this->entity == 'advertising'){
                	$folder = __DIR__ . '/../../../../../htdocs/assets/images/product/' . $this->id;
                	if(is_dir($folder)){
                	    $files = getFileList($folder);
                	    if($files != null){
                	    $files = getFileList($folder);
                			foreach(getFileList($folder) as $key => $image){
                			    $image['name'] = str_replace(__DIR__ . '/../../../../../htdocs', '', $image['name']);
                				echo '<img src="'.$image['name'].'" width="100px" alt="" class="img-rounded"> ';
                			}
                	    } else {
                		    echo '<img src="/assets/images/product/sem_foto.gif" width="100px" alt="" class="img-rounded">';
                	    }
                	} else {
                	    echo '<img src="/assets/images/product/sem_foto.gif" width="100px" alt="" class="img-rounded">';
                    } 
                } ?>
                </div>
                <div class="file"><?php echo $this->formFile($element) . $this->formElementErrors($element) ?></div>
            <?php elseif ($isCheckbox): ?>
                <div><?php echo $this->formCheckbox($element) ?></div>
            <?php else: ?>
                <div><?php echo $this->formInput($element) . $this->formElementErrors($element) ?></div>
            <?php endif ?>
        <?php endforeach ?>
    </div>
<?php if ($this->redirect): ?>
    <input type="hidiven" name="redirect" value="<?php echo $this->redirect ?>">
<?php endif ?>
    <div class="control-group">
        <br>
        <input type="submit" name="submit" value="Salvar" class="btn btn-primary">
    </div>
<?php echo $this->form()->closeTag() ?>