<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('class', 'form-horizontal');
// $form->setAttribute('action', $this->url('zfcadmin/zfcuseradmin/create'));
$form->setAttribute('method', 'post');
?>
<div class="container whiteBackground">
	<!-- Navegação Produto -->
	<div class="row">
		<div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 navegacaoProduto">
			<a href="#" class="pull-left">< Voltar para Página Inicial</a>
		</div>
		<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 navegacaoProduto">
			<a href="#" class="pull-right">Nova Busca ></a>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="headerTitle">
				<h1>Cadastro de Anúncios</h1>
			</div>
		</div>
	</div>
    <?php echo $this->form()->openTag($form)?>
    	<h1>Veiculo</h1>
    	<fieldset>
    	    <legend>Informações do Veículo</legend>
    		<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
    			<div class="form-group">
    				<?php echo $this->formLabel($form->get('typeItem')) ?>
    				<div class="col-sm-6">
    				    <?php echo $this->formSelect($form->get('typeItem')) . $this->formElementErrors($form->get('typeItem'))?>
    				</div>
    			</div>
    			<div class="form-group">
    				<?php echo $this->formLabel($form->get('brandN')) ?>
    				<div class="col-sm-6">
    				    <?php echo $this->formSelect($form->get('brandN')) . $this->formElementErrors($form->get('brandN'))?>
				    </div>
    			</div>
    			<div class="form-group">
					<?php echo $this->formLabel($form->get('model')) ?>
    				<div class="col-sm-6">
    				    <?php echo $this->formSelect($form->get('model')) . $this->formElementErrors($form->get('model'))?>
				    </div>
				</div>
    			<div class="form-group">
					<?php echo $this->formLabel($form->get('subType')) ?>
    				<div class="col-sm-6">
    				    <?php echo $this->formSelect($form->get('subType')) . $this->formElementErrors($form->get('subType'))?>
    				</div>
				</div>
    			<div class="form-group">
					<?php echo $this->formLabel($form->get('bodywork')) ?>
    				<div class="col-sm-6">
    				    <?php echo $this->formSelect($form->get('bodywork')) . $this->formElementErrors($form->get('bodywork'))?>
				    </div>
    			</div>
    			<div class="form-group">
    			    <label for="year" class="col-sm-4 control-label">Ano</label>
    				<div class="col-sm-6">
    				    <select name="year" id="year" class="form-control input-lg required">
    					    <option value="">Ano</option>
            			<?php for($i=2015;$i >= 1950;$i--) {?>
            				<option value="<?php echo $i ?>"><?php echo $i ?></option>
            				<?php } ?>
            			</select>
        			</div>
    			</div>
    			<div class="form-group">
					<?php echo $this->formLabel($form->get('color')) ?>
    				<div class="col-sm-6">
    				    <?php echo $this->formInput($form->get('color')) . $this->formElementErrors($form->get('color'))?>
				    </div>
				</div>
    			<div class="form-group">
    			    <label for="fuel" class="col-sm-4 control-label">Combustível</label>
    				<div class="col-sm-6">
    				    <select name="fuel" id="fuel" class="form-control input-lg required">
        					<option value="">Combustível</option>
                    		<?php
                                $fuels = array(
                                    '1' => 'Gasolina',
                                    '2' => 'Álcool',
                                    '3' => 'Diesel',
                                    '4' => 'Biodiesel',
                                    '5' => 'Outros'
                                );
                                foreach ($fuels as $key => $fuel) {
                                    echo '<option value="' . $key . '">' . $fuel . '</option>';
                                }
                            ?>
                        </select>
                    </div>
    			</div>
    			<div class="form-group">
    			    <label for="gear" class="col-sm-4 control-label">Transmissão</label>
    				<div class="col-sm-6">
    				    <select name="gear" id="gear" class="form-control input-lg required">
        					<option value="">Transmissão</option>
                    		<?php
                                $gears = array(
                                    '1' => 'Manual',
                                    '2' => 'Automático',
                                );
                                foreach ($gears as $key => $gear) {
                                    echo '<option value="' . $key . '">' . $gear . '</option>';
                                }
                            ?>
                        </select>
                    </div>
    			</div>
    			<div class="form-group">
    			<label for="new" class="col-sm-4 control-label">Estado do veículo</label>
    			<span class="col-sm-1 control-label"></span>
    			    <label class="radio-inline">
                      <input type="radio" name="new" id="new1" value="1" class="required"> Novo
                    </label>
                    <label class="radio-inline">
                      <input type="radio" name="new" id="new2" value="0" class="required"> Usado
                    </label>
    			</div>
    			<div class="form-group">
    				<?php echo $this->formLabel($form->get('km')) ?>
    				<div class="col-sm-6">
    				    <?php echo $this->formInput($form->get('km')) . $this->formElementErrors($form->get('km'))?>
				    </div>
    			</div>
    			<div class="form-group">
					<?php echo $this->formLabel($form->get('value')) ?>
    				<div class="col-sm-6">
    				    <?php echo $this->formInput($form->get('value')) . $this->formElementErrors($form->get('value'))?>
				    </div>
				</div>
    
    			<div class="form-group">
    				<h4>SELECIONE OS ACESSÓRIOS</h4>
    				<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
    				    <div class="checkbox">
    				        <?php echo $this->formMultiCheckbox($form->get('options')) . $this->formElementErrors($form->get('options'))?>
				        </div>
					</div>
				</div>
				
    		</div>
    	</fieldset>
    
    	<h1>Endereço</h1>
    	<fieldset>
    	    <legend>Informações do Endereço</legend>
    		<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
    			<div class="form-group">
					<?php echo $this->formLabel($form->get('address')) ?>
    				<div class="col-sm-6">
    				   <?php echo $this->formInput($form->get('address')) . $this->formElementErrors($form->get('address'))?>
				   </div>
				</div>
    			<div class="form-group">
					<?php echo $this->formLabel($form->get('number')) ?>
    				<div class="col-sm-6">
    				   <?php echo $this->formInput($form->get('number')) . $this->formElementErrors($form->get('number'))?>
				   </div>
				</div>
    			<div class="form-group">
					<?php echo $this->formLabel($form->get('complement')) ?>
    				<div class="col-sm-6">
    				   <?php echo $this->formInput($form->get('complement')) . $this->formElementErrors($form->get('complement'))?>
				   </div>
				</div>
    			<div class="form-group">
					<?php echo $this->formLabel($form->get('state')) ?>
    				<div class="col-sm-6">
    				    <?php echo $this->formSelect($form->get('state')) . $this->formElementErrors($form->get('state'))?>
				    </div>
				</div>
    			<div class="form-group">
					<label for="fuel" class="col-sm-4 control-label">Cidade</label>
        				<div class="col-sm-6">
            				<select name="city" id="city" class="form-control input-lg">
            				</select>
        				</div>
        			</div>
    			<div class="form-group">
					<?php echo $this->formLabel($form->get('district_name')) ?>
    				<div class="col-sm-6">
    				    <?php echo $this->formInput($form->get('district_name')) . $this->formElementErrors($form->get('district_name'))?>
				    </div>
				</div>
    			<div class="form-group">
					<?php echo $this->formLabel($form->get('contact-number')) ?>
    				<div class="col-sm-6">
    				    <?php echo $this->formInput($form->get('contact-number')) . $this->formElementErrors($form->get('contact-number'))?>
				    </div>
    			</div>
    		</div>
    	</fieldset>
    
    	<h1>Anúncio</h1>
    	<fieldset>
    	    <legend>Digite o seu anúncio</legend>
    		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    			<div class="form-group">
					<?php echo $this->formLabel($form->get('text')) ?>
    				<div class="col-sm-8">
						<?php echo $this->formTextarea($form->get('text')) . $this->formElementErrors($form->get('text'))?>
					</div>
				</div>
    			<div class="form-group">
					<?php echo $this->formLabel($form->get('image-file')) ?>
    				<div class="col-sm-8">
						<?php echo $this->formFile($form->get('image-file')) . $this->formElementErrors($form->get('image-file'))?>
					</div>
				</div>
    		</div>
    	</fieldset>
    <?php echo $this->form()->closeTag()?>
</div>
<!-- Form Actions -->
<script src="/assets/js/jquery.steps.js"></script>
<script src="/assets/js/jquery.validate.js"></script>
<script src="/assets/js/form.actions.js"></script>
<script>
var form = $("#newAdvertisingUserSteps").show();  
form.validate({
    errorPlacement: function errorPlacement(error, element) { element.before(error); },
    rules: {
        confirm: {
            //equalTo: "#password"
        }
    }
});                      
form.steps({
    	headerTag: "h1",
    	bodyTag: "fieldset",
    	labels: {
            cancel: "Cancelar",
            current: "current step:",
            finish: "Finalizar",
            next: "Próximo",
            previous: "Anterior",
            loading: "Carregando ..."
        },
        transitionEffect: "slideLeft",
        onStepChanging: function (event, currentIndex, newIndex)
        {
            form.validate().settings.ignore = ":disabled,:hidden";
            return form.valid();
        },
        onFinishing: function (event, currentIndex)
        {
            form.validate().settings.ignore = ":disabled";
            return form.valid();
        },
        onFinished: function (event, currentIndex)
        {
        	return form.submit();
        }
    });
</script>