<?php
$form = $this->form;
$form->prepare();
//$form->setAttribute('action', $this->url('zfcadmin/zfcuseradmin/create'));
$form->setAttribute('method', 'post');
?>
<div class="container whiteBackground">
	<!-- Navegação Produto -->
	<div class="row">
		<div class="col-xs-9 col-sm-9 col-md-9 col-lg-9 navegacaoProduto">
			<a href="#" class="pull-left">< Voltar para Página Inicial</a>
		</div>
		<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 navegacaoProduto">
			<a href="#" class="pull-right">Nova Busca ></a>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="headerTitle">
				<h1>Cadastro de Anúncios</h1>
			</div>
		</div>
	</div>
	<?php echo $this->form()->openTag($form) ?>
		<div class="row">
			<div class="col-md-12">
				<section style="background: #efefe9;">
					<div class="board">
						<!--BEM VINDO AO REGISTRO DE ANUNCIOS!-->
						<div class="board-inner">
							<ul class="nav nav-tabs" id="myTab">
								<div class="liner"></div>
								<li class="active"><a href="#home" data-toggle="tab"
									title="Passo 1 - Preencha o seu Anúncio"> <span
										class="round-tabs one"> <i class="glyphicon glyphicon-home"></i>
									</span>
								</a></li>

								<li><a href="#profile" data-toggle="tab"
									title="Passo 2 - Informe as suas Informações"> <span
										class="round-tabs two"> <i class="glyphicon glyphicon-globe"></i>
									</span>
								</a></li>
								<li><a href="#imagens" data-toggle="tab"
									title="Passo 3 - Adicione as Imagens e Publique!"> <span
										class="round-tabs three"> <i
											class="glyphicon glyphicon-picture"></i>
									</span>
								</a></li>


							</ul>
						</div>

						<div class="tab-content">
							<div class="tab-pane fade in active" id="home">
							<?php /* ?>
								<section class="col-md-6 registerMenu">
									<ul>
										<li><a href="caminhoes.html" class="caminhoes active">Caminhões</a></li>
										<li><a href="cavalos.html" class="cavalos">Cavalos</a></li>
										<li><a href="onibus.html" class="onibus">Ônibus</a></li>
										<li><a href="utilitarios.html" class="utilitarios">Utilitários/Vans</a></li>
										<li><a href="carretas.html" class="carretas">Carretas/Implementos</a></li>
										<li><a href="acessorios.html" class="acessorios">Acessórios</a></li>
										<li><a href="insumos.html" class="insumos">Insumos e Peças</a></li>
									</ul>
								</section>
								<?php */ ?>
								<section class="col-md-6">
									<div class="boxFormulario">

										<h3>Preencha os dados do item a ser anunciado</h3>
										<div class="clearfix"></div>
										<div id="loadRegisterForm">
										    <div>
												<span class="selectOption"><span id="brand">Tipo</span>
												<?php echo $this->formSelect($form->get('typeItem')) . $this->formElementErrors($form->get('typeItem')) ?>
												</span>
											</div>
											<div>
												<?php echo $this->formInput($form->get('km')) . $this->formElementErrors($form->get('km')) ?>
											</div>

											<div>
												<span class="inputRadio" data-input-id="situacao"
													data-input-value="1"> <input type="hidden" name="situacao"
													id="situacao" />
												</span>
											</div>
											<div>
												<span class="selectOption"><span id="brand">Marca</span>
												<?php echo $this->formSelect($form->get('brand')) . $this->formElementErrors($form->get('brand')) ?>
												</span>
											</div>
											<div>
												<span class="selectOption"> <span id="modelo">Modelo</span>
													<?php echo $this->formSelect($form->get('model')) . $this->formElementErrors($form->get('model')) ?>
												</span>
											</div>
											<div>
												<span class="selectOption"> <span id="tipo">Tipo</span>
												    <?php echo $this->formSelect($form->get('subType')) . $this->formElementErrors($form->get('subType')) ?>
												</span>
											</div>
											<div>
												<span class="inputRadio" data-input-id="cambio"
													data-input-value="1"> <input type="hidden" name="cambio"
													id="cambio" />
												</span> <label for="cambio_automatico">Automático</label> <span
													class="inputRadio" data-input-id="cambio"
													data-input-value="2"></span> <label for="cambio_manual">Manual</label>
											</div>
											<div>
												<span class="selectOption"> <span id="year">Selecionar Ano</span>
													<select name="year" data-text-id="year">
                                        			<?php for($i=2015;$i >= 1950;$i--) {?>
                                        				<option
															value="<?php echo $i ?>"><?php echo $i ?></option>
                                        				<?php } ?>
                                        			</select>
												</span>
											</div>
											<div>
												<?php echo $this->formInput($form->get('color')) . $this->formElementErrors($form->get('color')) ?>
											</div>
											<div>
												<span class="selectOption"> <span id="fuel">Selecionar
														Combustivel</span> <select name="fuel" data-text-id="fuel">
        											    <?php
                    
                    $fuels = array(
                        '1' => 'Gasolina',
                        '2' => 'Álcool',
                        '3' => 'Diesel',
                        '4' => 'Biodiesel',
                        '5' => 'Outros'
                    );
                    foreach ($fuels as $key => $fuel) {
                        echo '<option value="' . $key . '">' . $fuel . '</option>';
                    }
                    ?>
                                                    </select>
												</span>
											</div>
											<div>
												<span class="selectOption"> <span id="carroceria">Carroceria</span>
													<?php echo $this->formSelect($form->get('bodywork')) . $this->formElementErrors($form->get('bodywork')) ?>
												</span>
											</div>
											<div>
												<input placeholder="Digite o Valor" name="value" type="text">
											</div>

											<div>

												<h4>SELECIONE OS ACESSÓRIOS</h4>
												<span class="inputRadio" data-input-id="acessorios"
													data-input-value="1"> <input type="hidden"
													name="acessorios" id="acessorios" />
												</span> <label for="ar-condicionado">AR CONDICIONADO</label>
												<span class="inputRadio" data-input-id="acessorios"
													data-input-value="2"></span> <label for="interclima">INTERCLIMA</label>

											</div>
											<a href="#profile" data-toggle="tab"
												title="Passo 2 - Informe as suas Informações"> <input
												type="submit" value="AVANÇAR" />
											</a>
											<!-- Form Actions -->
											<script src="/assets/js/form.actions.js"></script>
										</div>

									</div>
									<br>

								</section>
							</div>
							<div class="tab-pane fade" id="profile">

								<div class="row">
									<div
										class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
										<fieldset>
											<hr class="colorgraph">

											<div class="form-group">
												<?php echo $this->formInput($form->get('address')) . $this->formElementErrors($form->get('address')) ?>
												<?php echo $this->formInput($form->get('number')) . $this->formElementErrors($form->get('number')) ?>
												<?php echo $this->formInput($form->get('complement')) . $this->formElementErrors($form->get('complement')) ?>
											</div>
											<div class="form-group">
												<?php echo $this->formInput($form->get('district_name')) . $this->formElementErrors($form->get('district_name')) ?>
											</div>
											<div class="form-group">
												<?php echo $this->formSelect($form->get('city')) . $this->formElementErrors($form->get('city')) ?>
											</div>
											<div class="form-group">
												<input type="text" name="estado" id="estado"
													class="form-control input-lg" placeholder="Estado">
											</div>

											<hr class="colorgraph">

										</fieldset>

										<p class="text-center">
											<a href="#imagens" data-toggle="tab"
												title="Passo 3 - Adicione as Imagens e Publique!"
												class="btn btn-success btn-outline-rounded green"> AVANÇAR </span>
											</a>
										</p>
									</div>
								</div>
							</div>
							<div class="tab-pane fade" id="imagens">
								<div class="row">
									<div
										class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
										<h3 class="head text-center">ADICIONE AS IMAGENS DO SEU
											PRODUTO</h3>
										<fieldset>
											<div class="form-group">
												<p class="narrow text-center">Lorem ipsum dolor sit amet,
													his ea mollis fabellas principes. Quo mazim facilis
													tincidunt ut, utinam saperet facilisi an vim.</p>
												<label for="name"> Descreva o seu Anúncio</label>
												<?php echo $this->formTextarea($form->get('text')) . $this->formElementErrors($form->get('text')) ?>
												<input type="submit"
													class="btn btn-success btn-outline-rounded green"
													value="Publicar Anúncio">
											</div>

										</fieldset>
									</div>
								</div>
							</div>
							<div class="clearfix"></div>
						</div>

					</div>
			
			</div>
		</div>
	<?php echo $this->form()->closeTag() ?>
</div>
<!-- Form Actions -->
<script src="/assets/js/form.actions.js"></script>