<div class="row">
						<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
							<div class="row">
								<section class="col-xs-12 col-sm-12 col-md-12 col-lg-12 searchMenu">
									<ul>
										<li><a href="caminhoes.html" class="caminhoes active">Caminhões</a></li>
										<li><a href="cavalos.html" class="cavalos">Cavalos</a></li>
										<li><a href="onibus.html" class="onibus">Ônibus</a></li>
										<li><a href="utilitarios.html" class="utilitarios">Utilitários/Vans</a></li>
										<li><a href="carretas.html" class="carretas">Carretas/Implementos</a></li>
										<li><a href="acessorios.html" class="acessorios">Acessórios</a></li>
										<li><a href="insumos.html" class="insumos">Insumos e Peças</a></li>
									</ul>
								</section>
								<section class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<div class="boxPublicacoes">
										<h1>Publicações e Ofertas</h1>
										<p><?php echo $this->carCnt; ?> | Veículos</p>
										<p><?php echo $this->cartCnt; ?> | Carretas e Implementos</p>
										<p><?php echo $this->acCnt; ?> | Acessórios e Implementos</p>
									</div>
								</section>
							</div>
						</div>
						<section class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
							<div class="boxFormulario">

								<h1>Comprar</h1>
								<!-- a href="#" class="buscaAvancada">> Busca Avançada</a -->
								<div class="clearfix"></div>
								<div id="loadForm">
									<form action="/result" method="POST">
										<div>
											<span class="inputRadio" data-input-id="situacao" data-input-value="1">
												<input type="hidden" name="situacao" id="situacao"/>
											</span>
											<label for="estado">O Km</label>
											<span class="inputRadio" data-input-id="situacao" data-input-value="2"></span>
											<label for="tipo">Usado</label>
										</div>
										<div>
											<span class="selectOption">
												<span id="marca">Marca</span>
												<select name="marca" data-text-id="marca">
													<option value="">Marca</option>
													<option value="Fiat">Fiat</option>
													<option value="">Ford</option>
												</select>
											</span>
										</div>
										<div>
											<span class="selectOption">
												<span id="modelo">Modelo</span>
												<select name="modelo" data-text-id="modelo">
													<option value="">Modelo</option>
												</select>
											</span>
										</div>
										<div>
											<span class="selectOption">
												<span id="tipo">Tipo</span>
												<select name="tipo" data-text-id="tipo">
													<option value="">Tipo</option>
												</select>
											</span>
										</div>
										<div>
											<span class="inputRadio" data-input-id="cambio" data-input-value="1">
												<input type="hidden" name="cambio" id="cambio"/>
											</span>
											<label for="cambio_automatico">Automático</label>
											<span class="inputRadio" data-input-id="cambio" data-input-value="2"></span>
											<label for="cambio_manual">Manual</label>
										</div>
										<div>
											ano
											<input type="text" name="ano_fim" placeholder="até" class="duo">
											<input type="text" name="ano" placeholder="de" class="duo">
											<br/><br/>
										</div>
										<div>
											<span class="selectOption">
												<span id="uf">Estado</span>
												<select name="uf" data-text-id="uf">
													<option value="">Estado</option>
												</select>
											</span>
										</div>
										<div>
											<span class="selectOption">
												<span id="cidade">Cidade</span>
												<select name="cidade" data-text-id="cidade">
													<option value="">Cidade</option>
												</select>
											</span>
										</div>
										<div>
											<span class="selectOption">
												<span id="carroceria">Carroceria</span>
												<select name="carroceria" data-text-id="carroceria">
													<option value="">Carroceria</option>
												</select>
											</span>
										</div>
										<div>
											valor
											<input type="text" name="ano_fim" placeholder="até" class="duo">
											<input type="text" name="ano" placeholder="de" class="duo">
										</div>
										<input type="submit" value="Buscar"/>
									</form>
								</div>
							</div>
						</section>
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-4">
							<div class="row">
								<section class="col-xs-12 col-sm-6 col-md-6 col-lg-12 mTop15">
									<a href="<?php echo$this->url('novo-anuncio') ?>" class="btnPublicarAnuncio">Publicar Anúncio</a>
								</section>
								<section class="col-xs-12 col-sm-6 col-md-6 col-lg-12 mTop15">
									<p class="txtPublicarCurriculo hidden-md hidden-sm hidden-xs">Publique seu currículo e aumente suas chances de recolocação.</p>
									<a href="#" class="btnPublicarCurriculo">Publicar Currículo</a>
								</section>
								<section class="col-xs-12 col-sm-6 col-md-6 col-lg-12">
									<div class="boxVideos">
										<h1>VÍDEOS BRIKeBRAK</h1>
										<a href="#" class="vejaMais">Veja Mais ></a>
										<div class="ytPlayer embed-responsive embed-responsive-16by9">
											<iframe class="embed-responsive-item" src="http://www.youtube.com/embed/3EYuOsqI65o" frameborder="0" allowfullscreen></iframe>
										</div>
										<p class="videoTitulo">Nova linha de caminhões 2014 da mercedes bens</p>
										<div class="paginacao">
											<a href="#" class="first"><</a>
											<a href="#" class="middle"><span>1</span></a>
											<a href="#" class="middle"><span>2</span></a>
											<a href="#" class="middle"><span>3</span></a>
											<a href="#" class="middle"><span>4</span></a>
											<a href="#" class="last">></a>
										</div>
									</div>
								</section>
								<section class="col-xs-12 col-sm-6 col-md-6 col-lg-12">
									<div class="boxTabelas">
										<div class="tabelaFipe">
											<h2>Tabela <b>FIPE</b>:<br/>Avalie seu caminhão</h2>
											<p><a href="#">Preço médio do veículo<br/>de acordo com o mercado ></a></p>
										</div>
										<div class="simulador">
											<h2>Simule seu<br/>financiamento</h2>
											<p><a href="#">Simule o financiamento que melhor<br>se encaixa no seu bolso ></a></p>
										</div>
									</div>
								</section>
							</div>
						</div>
					</div>