<?php
$form = $this->changePasswordForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');

echo $this->form()->openTag($form)
?>
<fieldset>
    <legend>Change Password for <?php echo $this->zfcUserDisplayName(); ?></legend>

    <?php echo $this->formHidden($form->get('identity')); ?>
    
    <?php $form->get('credential')->setAttribute('class','form-control'); ?>
    <?php $form->get('credential')->setLabelAttributes(array('class' => 'control-label col-lg-2')); ?>
    <div class="form-group <?php if ($this->formElementErrors($form->get('credential'))) echo 'has-error'; ?>">
        <?php echo $this->formLabel($form->get('credential')); ?>
            <div class="input-group col-lg-3">
                <span class="input-group-addon glyphicon glyphicon-lock"></span>
                <?php echo $this->formInput($form->get('credential')) ?>
            </div>
            <?php echo $this->formElementErrors()
                    ->setMessageOpenFormat('<span class="help-block">')
                    ->setMessageSeparatorString('</span><span class="help-block">')
                    ->setMessageCloseString('</span>')
                    ->render($form->get('credential')); ?>
    </div>
    
    <?php $form->get('newCredential')->setAttribute('class','form-control'); ?>
    <?php $form->get('newCredential')->setLabelAttributes(array('class' => 'control-label col-lg-2')); ?>
    <div class="form-group <?php if ($this->formElementErrors($form->get('newCredential'))) echo 'has-error'; ?>">
        <?php echo $this->formLabel($form->get('newCredential')); ?>
            <div class="input-group col-lg-3">
                <span class="input-group-addon glyphicon glyphicon-lock"></span>
                <?php echo $this->formInput($form->get('newCredential')) ?>
            </div>
            <?php echo $this->formElementErrors()
                    ->setMessageOpenFormat('<span class="help-block">')
                    ->setMessageSeparatorString('</span><span class="help-block">')
                    ->setMessageCloseString('</span>')
                    ->render($form->get('newCredential')); ?>
    </div>
    
    <?php $form->get('newCredentialVerify')->setAttribute('class','form-control'); ?>
    <?php $form->get('newCredentialVerify')->setLabelAttributes(array('class' => 'control-label col-lg-2')); ?>
    <div class="form-group <?php if ($this->formElementErrors($form->get('newCredentialVerify'))) echo 'has-error'; ?>">
        <?php echo $this->formLabel($form->get('newCredentialVerify')); ?>
            <div class="col-lg-3">
                <div class="input-group">
                    <span class="input-group-addon glyphicon glyphicon-lock"></span>
                    <?php echo $this->formInput($form->get('newCredentialVerify')) ?>
                </div>
                <?php echo $this->formElementErrors()
                        ->setMessageOpenFormat('<span class="help-block">')
                        ->setMessageSeparatorString('</span><span class="help-block">')
                        ->setMessageCloseString('</span>')
                        ->render($form->get('newCredentialVerify')); ?>
            </div>
    </div>
    
    <?php $form->get('submit')->setAttribute('class', 'btn btn-primary') ?>
    <div class="form-group">
        <div class="col-lg-3 col-lg-offset-2">
            <?php echo $this->formInput($form->get('submit')); ?>
        </div>
    </div>
    
</fieldset>
<?php echo $this->form()->closeTag() ?>